$axure.loadCurrentPage({
  "url":"achievement.html",
  "generationDate":new Date(1446176365274.22),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable",
"isHiden",
"isHiden2",
"text",
"separater",
"isstarted",
"isshown",
"showpicture"],
  "page":{
    "packageId":"cda11b747e734560912347ae483b184f",
    "type":"Axure:Page",
    "name":"achievement",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"c58155a797584926ac39d625c75ba0e0",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "disabled":true,
          "visible":true,
          "style":{
            "size":{
              "width":1348,
              "height":1200}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a8555a2f08814660b2926e6f3009e1bb",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "disabled":true,
              "visible":true,
              "style":{
                "size":{
                  "width":1348,
                  "height":1200}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/home/u0.jpg"}},
{
          "id":"f98fd6562daf4cf2b30c8b2956003caa",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "disabled":true,
          "visible":true,
          "style":{
            "location":{
              "x":490.5,
              "y":0},
            "size":{
              "width":385,
              "height":793},
            "borderWidth":"-1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF000000}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"2427b4d4262d44e6aee96dbe34349478",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "disabled":true,
              "visible":true,
              "style":{
                "location":{
                  "x":490.5,
                  "y":0},
                "size":{
                  "width":385,
                  "height":793},
                "borderWidth":"-1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF000000}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/home/u2.png"}},
{
          "id":"3bdfc07a764546f6bef8d1cfbdb31da1",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":522,
              "y":173},
            "size":{
              "width":320,
              "height":507}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d146377bae984785b12bbf078d97ac72",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":522,
                  "y":173},
                "size":{
                  "width":320,
                  "height":507}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/pravite/u4.png"}},
{
          "id":"d0737ad17a7b449692cfc5ba0efa2f4f",
          "label":"状态栏",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFFF6666},
            "location":{
              "x":522,
              "y":113},
            "size":{
              "width":320,
              "height":20},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFF6666}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4168b37bee1140fc84f02e48af1b9625",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFF6666},
                "location":{
                  "x":522,
                  "y":113},
                "size":{
                  "width":320,
                  "height":20},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFF6666}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/home/状态栏_u31.png"}},
{
          "id":"9fb14f0bbaf34d5eba67a12876132091",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Charlemagne Std Bold', 'Charlemagne Std'",
            "fontSize":"14px",
            "fontWeight":"700",
            "lineSpacing":"20px",
            "fill":{
              "fillType":"solid",
              "color":0xFFFF6666},
            "location":{
              "x":522,
              "y":133},
            "size":{
              "width":320,
              "height":40},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFF6666}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"6d45f2fe7e6e42bca31f12392ac7d473",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Charlemagne Std Bold', 'Charlemagne Std'",
                "fontSize":"14px",
                "fontWeight":"700",
                "lineSpacing":"20px",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFF6666},
                "location":{
                  "x":522,
                  "y":133},
                "size":{
                  "width":320,
                  "height":40},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFF6666}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/home/框架_u33.png"}},
{
          "id":"8e18013fff5d4126a9fe83992e6ea605",
          "label":"消息",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":532,
              "y":143},
            "size":{
              "width":25,
              "height":25}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"34e2d4ca451f49059357e9e2294a6214",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":532,
                  "y":143},
                "size":{
                  "width":25,
                  "height":25}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 Home",
                      "target":{
                        "targetType":"page",
                        "url":"home.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/pravite/消息_u44.png"}},
{
          "id":"328844b4ddad42d89c3a831aa9ac321e",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "fontSize":"20px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "location":{
              "x":642,
              "y":139},
            "size":{
              "width":81,
              "height":27}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ceaaaf0eb9954622b92e627a107c1cac",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "fontSize":"20px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "location":{
                  "x":642,
                  "y":139},
                "size":{
                  "width":81,
                  "height":27}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"71f90189e52d40be99e60e4c2dd9bdb9",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Charlemagne Std Bold', 'Charlemagne Std'",
            "fontSize":"14px",
            "fontWeight":"700",
            "lineSpacing":"20px",
            "fill":{
              "fillType":"solid",
              "color":0xFFCCCCCC},
            "location":{
              "x":522,
              "y":173},
            "size":{
              "width":320,
              "height":470},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFF6666}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"0832d5aae4bc4e8b86f1944e8ebe6269",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Charlemagne Std Bold', 'Charlemagne Std'",
                "fontSize":"14px",
                "fontWeight":"700",
                "lineSpacing":"20px",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC},
                "location":{
                  "x":522,
                  "y":173},
                "size":{
                  "width":320,
                  "height":470},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFF6666}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/achievement/u14.png"}},
{
          "id":"68164234babb44d48bf2b5c77312deac",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":532,
              "y":183},
            "size":{
              "width":100,
              "height":100}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f283d1bd1148482d8a96294e8928d0db",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":532,
                  "y":183},
                "size":{
                  "width":100,
                  "height":100}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/achievement/u16.png"}},
{
          "id":"2d4142724c6e48b4b158b9df4f7a3e23",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":642,
              "y":193},
            "size":{
              "width":100,
              "height":100}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"85121244dfba4eaabd86e9d547c20894",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":642,
                  "y":193},
                "size":{
                  "width":100,
                  "height":100}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/achievement/u18.png"}},
{
          "id":"481beb2464294101b698fe7ba9eb17c6",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":732,
              "y":183},
            "size":{
              "width":100,
              "height":100}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e74a67073f7447d382c9f71da9c9410d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":732,
                  "y":183},
                "size":{
                  "width":100,
                  "height":100}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/achievement/u20.png"}},
{
          "id":"768afde7daba45819578a83f30e47890",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":532,
              "y":293},
            "size":{
              "width":100,
              "height":100}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5498d84579cb4d8f944f46b13f43663b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":532,
                  "y":293},
                "size":{
                  "width":100,
                  "height":100}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/achievement/u22.png"}},
{
          "id":"cdedda42ba21414081374c745450725f",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":642,
              "y":293},
            "size":{
              "width":100,
              "height":100}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"95d2592262724f1c811f0dfcdecca87d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":642,
                  "y":293},
                "size":{
                  "width":100,
                  "height":100}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/achievement/u24.png"}},
{
          "id":"077f3cac98cf4e52a03e8c8e0e695da5",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":542,
              "y":403},
            "size":{
              "width":100,
              "height":100}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"64b5a6314d514fc7845a82f076fc8fdd",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":542,
                  "y":403},
                "size":{
                  "width":100,
                  "height":100}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/achievement/u26.png"}},
{
          "id":"b37ab0e580e84d40bd5d1f1add8df052",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":732,
              "y":293},
            "size":{
              "width":100,
              "height":100}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"6558d320518c4ebda66bebdf6e676fb2",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":732,
                  "y":293},
                "size":{
                  "width":100,
                  "height":100}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/achievement/u28.png"}},
{
          "id":"cacf1658b8a1441c931573913922e8f1",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":642,
              "y":403},
            "size":{
              "width":100,
              "height":100}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"246c7f7574424e5ba202aadecbc0961f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":642,
                  "y":403},
                "size":{
                  "width":100,
                  "height":100}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/achievement/u30.png"}},
{
          "id":"bd19a9bf7a044b5cae7954764a99bb93",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":732,
              "y":403},
            "size":{
              "width":100,
              "height":100}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"654a6d2be81a4d28aeb081b7f9e5eee9",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":732,
                  "y":403},
                "size":{
                  "width":100,
                  "height":100}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/achievement/u32.png"}},
{
          "id":"2ef154d156a8413394724f0226353ab0",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":542,
              "y":513},
            "size":{
              "width":100,
              "height":100}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"08528bd1f7444d48831b06ebf0fa6c66",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":542,
                  "y":513},
                "size":{
                  "width":100,
                  "height":100}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/achievement/u34.png"}},
{
          "id":"53dd3e47e6e2440facaeb3c00599b081",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":672,
              "y":513},
            "size":{
              "width":100,
              "height":100}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7d7f960d70eb4c1cb0253d3de9a56504",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":672,
                  "y":513},
                "size":{
                  "width":100,
                  "height":100}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/achievement/u18.png"}},
{
          "id":"3e6119902913440793e5234c60ac8ec2",
          "label":"消息",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":802,
              "y":133},
            "size":{
              "width":25,
              "height":30}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4be11e088a354ea5b914761f04e0f451",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":802,
                  "y":133},
                "size":{
                  "width":25,
                  "height":30}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/achievement/消息_u38.png"}}]}},
  "masters":{
},
  "objectPaths":{
    "c58155a797584926ac39d625c75ba0e0":{
      "scriptId":"u0"},
    "a8555a2f08814660b2926e6f3009e1bb":{
      "scriptId":"u1"},
    "f98fd6562daf4cf2b30c8b2956003caa":{
      "scriptId":"u2"},
    "2427b4d4262d44e6aee96dbe34349478":{
      "scriptId":"u3"},
    "3bdfc07a764546f6bef8d1cfbdb31da1":{
      "scriptId":"u4"},
    "d146377bae984785b12bbf078d97ac72":{
      "scriptId":"u5"},
    "d0737ad17a7b449692cfc5ba0efa2f4f":{
      "scriptId":"u6"},
    "4168b37bee1140fc84f02e48af1b9625":{
      "scriptId":"u7"},
    "9fb14f0bbaf34d5eba67a12876132091":{
      "scriptId":"u8"},
    "6d45f2fe7e6e42bca31f12392ac7d473":{
      "scriptId":"u9"},
    "8e18013fff5d4126a9fe83992e6ea605":{
      "scriptId":"u10"},
    "34e2d4ca451f49059357e9e2294a6214":{
      "scriptId":"u11"},
    "328844b4ddad42d89c3a831aa9ac321e":{
      "scriptId":"u12"},
    "ceaaaf0eb9954622b92e627a107c1cac":{
      "scriptId":"u13"},
    "71f90189e52d40be99e60e4c2dd9bdb9":{
      "scriptId":"u14"},
    "0832d5aae4bc4e8b86f1944e8ebe6269":{
      "scriptId":"u15"},
    "68164234babb44d48bf2b5c77312deac":{
      "scriptId":"u16"},
    "f283d1bd1148482d8a96294e8928d0db":{
      "scriptId":"u17"},
    "2d4142724c6e48b4b158b9df4f7a3e23":{
      "scriptId":"u18"},
    "85121244dfba4eaabd86e9d547c20894":{
      "scriptId":"u19"},
    "481beb2464294101b698fe7ba9eb17c6":{
      "scriptId":"u20"},
    "e74a67073f7447d382c9f71da9c9410d":{
      "scriptId":"u21"},
    "768afde7daba45819578a83f30e47890":{
      "scriptId":"u22"},
    "5498d84579cb4d8f944f46b13f43663b":{
      "scriptId":"u23"},
    "cdedda42ba21414081374c745450725f":{
      "scriptId":"u24"},
    "95d2592262724f1c811f0dfcdecca87d":{
      "scriptId":"u25"},
    "077f3cac98cf4e52a03e8c8e0e695da5":{
      "scriptId":"u26"},
    "64b5a6314d514fc7845a82f076fc8fdd":{
      "scriptId":"u27"},
    "b37ab0e580e84d40bd5d1f1add8df052":{
      "scriptId":"u28"},
    "6558d320518c4ebda66bebdf6e676fb2":{
      "scriptId":"u29"},
    "cacf1658b8a1441c931573913922e8f1":{
      "scriptId":"u30"},
    "246c7f7574424e5ba202aadecbc0961f":{
      "scriptId":"u31"},
    "bd19a9bf7a044b5cae7954764a99bb93":{
      "scriptId":"u32"},
    "654a6d2be81a4d28aeb081b7f9e5eee9":{
      "scriptId":"u33"},
    "2ef154d156a8413394724f0226353ab0":{
      "scriptId":"u34"},
    "08528bd1f7444d48831b06ebf0fa6c66":{
      "scriptId":"u35"},
    "53dd3e47e6e2440facaeb3c00599b081":{
      "scriptId":"u36"},
    "7d7f960d70eb4c1cb0253d3de9a56504":{
      "scriptId":"u37"},
    "3e6119902913440793e5234c60ac8ec2":{
      "scriptId":"u38"},
    "4be11e088a354ea5b914761f04e0f451":{
      "scriptId":"u39"}}});