$axure.loadCurrentPage({
  "url":"creating.html",
  "generationDate":new Date(1446176367513.02),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable",
"isHiden",
"isHiden2",
"text",
"separater",
"isstarted",
"isshown",
"showpicture"],
  "page":{
    "packageId":"aade53a4c16f41918728a2a6e308d348",
    "type":"Axure:Page",
    "name":"creating",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"5e7419bf99dd4bcd92244c2526e37aa5",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "disabled":true,
          "visible":true,
          "style":{
            "size":{
              "width":1348,
              "height":1200}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"020435abe1a0430ca0ab1f258f3efa5a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "disabled":true,
              "visible":true,
              "style":{
                "size":{
                  "width":1348,
                  "height":1200}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/home/u0.jpg"}},
{
          "id":"a8333f16c1b04dd59a096128c9738db8",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "disabled":true,
          "visible":true,
          "style":{
            "location":{
              "x":490.5,
              "y":0},
            "size":{
              "width":385,
              "height":793},
            "borderWidth":"-1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF000000}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"aa85e62f5fdd4b80afcc83303acd6f15",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "disabled":true,
              "visible":true,
              "style":{
                "location":{
                  "x":490.5,
                  "y":0},
                "size":{
                  "width":385,
                  "height":793},
                "borderWidth":"-1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF000000}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/home/u2.png"}},
{
          "id":"cac9c4d37b29422c8434fefcedf303ef",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":522,
              "y":173},
            "size":{
              "width":320,
              "height":507}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f0f4170899d84a238de23f6bd1657bb0",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":522,
                  "y":173},
                "size":{
                  "width":320,
                  "height":507}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/pravite/u4.png"}},
{
          "id":"d1163af39d7f418d8816e582fd9d93ac",
          "label":"状态栏",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFFF6666},
            "location":{
              "x":522,
              "y":113},
            "size":{
              "width":320,
              "height":20},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFF6666}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"6bd806fd865044e8b392bdb7b5c9a12b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFF6666},
                "location":{
                  "x":522,
                  "y":113},
                "size":{
                  "width":320,
                  "height":20},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFF6666}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/home/状态栏_u31.png"}},
{
          "id":"be1227c8c2804ee78782c50fa897ca8d",
          "label":"框架",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Charlemagne Std Bold', 'Charlemagne Std'",
            "fontSize":"14px",
            "fontWeight":"700",
            "lineSpacing":"20px",
            "fill":{
              "fillType":"solid",
              "color":0xFFFF6666},
            "location":{
              "x":522,
              "y":133},
            "size":{
              "width":320,
              "height":40},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFF6666}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ea3c3f10ec034f88b3a27c71c0e69bd8",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Charlemagne Std Bold', 'Charlemagne Std'",
                "fontSize":"14px",
                "fontWeight":"700",
                "lineSpacing":"20px",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFF6666},
                "location":{
                  "x":522,
                  "y":133},
                "size":{
                  "width":320,
                  "height":40},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFF6666}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/home/框架_u33.png"}},
{
          "id":"82dfb32048564fcc9e5d0eb280b42c56",
          "label":"消息",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":532,
              "y":143},
            "size":{
              "width":25,
              "height":25}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"2be246e684c94ee78f95910bc8175193",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":532,
                  "y":143},
                "size":{
                  "width":25,
                  "height":25}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 Home",
                      "target":{
                        "targetType":"page",
                        "url":"home.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/pravite/消息_u44.png"}},
{
          "id":"e1178358fe094a1ea91007477bf86828",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "fontSize":"20px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "location":{
              "x":642,
              "y":139},
            "size":{
              "width":81,
              "height":27}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"30dd5b15350a49acbf05160a2dc62fc3",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "fontSize":"20px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "location":{
                  "x":642,
                  "y":139},
                "size":{
                  "width":81,
                  "height":27}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"6f22a68a7a43462d898bade0d294d7b7",
          "label":"开始旅程",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":632,
              "y":413},
            "size":{
              "width":100,
              "height":30},
            "cornerRadiusTopLeft":"5"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"581e0980f5f648dfb91485dff929c847",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":632,
                  "y":413},
                "size":{
                  "width":100,
                  "height":30},
                "cornerRadiusTopLeft":"5"},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"setFunction",
                      "description":"设置 值于 isstarted = &quot;true&quot;",
                      "expr":{
                        "exprType":"block",
                        "subExprs":[{
                            "exprType":"fcall",
                            "functionName":"SetGlobalVariableValue",
                            "arguments":[{
                                "exprType":"globalVariableLiteral",
                                "variableName":"isstarted"},
{
                                "exprType":"stringLiteral",
                                "value":"true",
                                "stos":[]}]}]}},
{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 Home",
                      "target":{
                        "targetType":"page",
                        "url":"home.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/creating/开始旅程_u14.png"}},
{
          "id":"af80b674dc7e4684b6e6ffb0ae4887b1",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":652,
              "y":193},
            "size":{
              "width":60,
              "height":60}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"3d36c111a4df47439af250571aa5c671",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":652,
                  "y":193},
                "size":{
                  "width":60,
                  "height":60}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/home/u5.png"}},
{
          "id":"4b3c03a6223a46b99829c20244bc3362",
          "label":"相册名",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF999999,
              "opacity":1},
            "location":{
              "x":578,
              "y":273},
            "size":{
              "width":210,
              "height":25}},
          "adaptiveStyles":{
},
          "submitButton":{
            "path":[],
            "id":"6f22a68a7a43462d898bade0d294d7b7"},
          "placeholderText":"相册名"},
{
          "id":"ad4bfd3eeb3d427e91cbb8f42de21edd",
          "label":"",
          "type":"textArea",
          "styleType":"textArea",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF999999,
              "opacity":1},
            "location":{
              "x":578,
              "y":308},
            "size":{
              "width":210,
              "height":85}},
          "adaptiveStyles":{
},
          "submitButton":{
            "path":[],
            "id":"6f22a68a7a43462d898bade0d294d7b7"},
          "placeholderText":"相册描述"}]}},
  "masters":{
},
  "objectPaths":{
    "5e7419bf99dd4bcd92244c2526e37aa5":{
      "scriptId":"u0"},
    "020435abe1a0430ca0ab1f258f3efa5a":{
      "scriptId":"u1"},
    "a8333f16c1b04dd59a096128c9738db8":{
      "scriptId":"u2"},
    "aa85e62f5fdd4b80afcc83303acd6f15":{
      "scriptId":"u3"},
    "cac9c4d37b29422c8434fefcedf303ef":{
      "scriptId":"u4"},
    "f0f4170899d84a238de23f6bd1657bb0":{
      "scriptId":"u5"},
    "d1163af39d7f418d8816e582fd9d93ac":{
      "scriptId":"u6"},
    "6bd806fd865044e8b392bdb7b5c9a12b":{
      "scriptId":"u7"},
    "be1227c8c2804ee78782c50fa897ca8d":{
      "scriptId":"u8"},
    "ea3c3f10ec034f88b3a27c71c0e69bd8":{
      "scriptId":"u9"},
    "82dfb32048564fcc9e5d0eb280b42c56":{
      "scriptId":"u10"},
    "2be246e684c94ee78f95910bc8175193":{
      "scriptId":"u11"},
    "e1178358fe094a1ea91007477bf86828":{
      "scriptId":"u12"},
    "30dd5b15350a49acbf05160a2dc62fc3":{
      "scriptId":"u13"},
    "6f22a68a7a43462d898bade0d294d7b7":{
      "scriptId":"u14"},
    "581e0980f5f648dfb91485dff929c847":{
      "scriptId":"u15"},
    "af80b674dc7e4684b6e6ffb0ae4887b1":{
      "scriptId":"u16"},
    "3d36c111a4df47439af250571aa5c671":{
      "scriptId":"u17"},
    "4b3c03a6223a46b99829c20244bc3362":{
      "scriptId":"u18"},
    "ad4bfd3eeb3d427e91cbb8f42de21edd":{
      "scriptId":"u19"}}});