$axure.loadCurrentPage({
  "url":"pictures.html",
  "generationDate":new Date(1445067357314.93),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable",
"isHiden",
"isHiden2"],
  "page":{
    "packageId":"b4ddd2ceb4a34e81a0c8b648033f4456",
    "type":"Axure:Page",
    "name":"pictures",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"394d1121c6004909abe759cfce751e86",
          "label":"状态栏",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFFF6666},
            "size":{
              "width":320,
              "height":20},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFF6666}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"219b7ea8754749029785c44f801afd59",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFF6666},
                "size":{
                  "width":320,
                  "height":20},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFF6666}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/pravite/状态栏_u10.png"}},
{
          "id":"12a2e4b7ac694045a2af180729acb5d7",
          "label":"框架",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Charlemagne Std Bold', 'Charlemagne Std'",
            "fontSize":"14px",
            "fontWeight":"700",
            "lineSpacing":"20px",
            "fill":{
              "fillType":"solid",
              "color":0xFFFF6666},
            "location":{
              "x":0,
              "y":20},
            "size":{
              "width":320,
              "height":40},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFF6666}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"29068d3a8ddb491485144c289103c2c5",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Charlemagne Std Bold', 'Charlemagne Std'",
                "fontSize":"14px",
                "fontWeight":"700",
                "lineSpacing":"20px",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFF6666},
                "location":{
                  "x":0,
                  "y":20},
                "size":{
                  "width":320,
                  "height":40},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFF6666}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/pravite/u12.png"}},
{
          "id":"71979955f2aa41158e55a12616e61ef5",
          "label":"消息",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":10,
              "y":30},
            "size":{
              "width":25,
              "height":25}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"35c174d78b5f4706ae3439ffa8d88640",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":10,
                  "y":30},
                "size":{
                  "width":25,
                  "height":25}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 Home",
                      "target":{
                        "targetType":"page",
                        "url":"home.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/pravite/消息_u18.png"}},
{
          "id":"58d5db3d1366441f950edc66d7fb11aa",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "fontSize":"20px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "location":{
              "x":129.5,
              "y":26.5},
            "size":{
              "width":61,
              "height":27}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b9149d3637f24786a13f16e9b99c43d6",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "fontSize":"20px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "location":{
                  "x":129.5,
                  "y":26.5},
                "size":{
                  "width":61,
                  "height":27}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"b46fda283e9e4923bb4bd6cbbdb39026",
          "label":"",
          "type":"repeater",
          "styleType":"repeater",
          "visible":true,
          "style":{
            "location":{
              "x":0,
              "y":60},
            "size":{
              "width":250,
              "height":150}},
          "adaptiveStyles":{
},
          "interactionMap":{
            "onItemLoad":{
              "description":"OnItemLoad",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"setFunction",
                      "description":"设置 文字于 (形状) = &quot;[[Item.Column0]]&quot;",
                      "expr":{
                        "exprType":"block",
                        "subExprs":[{
                            "exprType":"fcall",
                            "functionName":"SetWidgetRichText",
                            "arguments":[{
                                "exprType":"pathLiteral",
                                "isThis":false,
                                "isFocused":false,
                                "isTarget":false,
                                "value":["f8872f336aee48e5a7d22e5728d69915"]},
{
                                "exprType":"stringLiteral",
                                "value":"[[Item.Column0]]",
                                "localVariables":{
},
                                "stos":[{
                                    "sto":"item",
                                    "name":"column0",
                                    "isTarget":false}]},
{
                                "exprType":"booleanLiteral",
                                "value":true}]}]}}]}]}},
          "repeaterPropMap":{
            "isolateRadio":true,
            "isolateSelection":true,
            "default":{
              "loadLocalDefault":true,
              "wrap":-1,
              "vertical":true,
              "horizontalSpacing":0,
              "verticalSpacing":0,
              "hasAltColor":false,
              "itemsPerPage":-1,
              "currPage":1,
              "backColor":{
                "r":255,
                "g":255,
                "b":255,
                "a":0},
              "altColor":{
                "r":255,
                "g":255,
                "b":255,
                "a":0}},
            "":{
              "width":320,
              "height":180,
              "loadLocalDefault":true,
              "wrap":-1,
              "vertical":true,
              "horizontalSpacing":0,
              "verticalSpacing":0,
              "hasAltColor":false,
              "itemsPerPage":-1,
              "currPage":1,
              "backColor":{
                "r":255,
                "g":255,
                "b":255,
                "a":0},
              "altColor":{
                "r":255,
                "g":255,
                "b":255,
                "a":0}}},
          "objects":[{
              "id":"cb13af9b609242b6990aa9d9f2c71b33",
              "label":"",
              "type":"buttonShape",
              "styleType":"buttonShape",
              "visible":true,
              "style":{
                "size":{
                  "width":320,
                  "height":180}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"f8872f336aee48e5a7d22e5728d69915",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "size":{
                      "width":320,
                      "height":180}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/pictures/u9.png"}},
{
              "id":"323ec501580946e39054b91722e05e47",
              "label":"",
              "type":"imageBox",
              "styleType":"imageBox",
              "visible":true,
              "style":{
                "location":{
                  "x":10,
                  "y":5},
                "size":{
                  "width":170,
                  "height":170}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"58a5521fa9fb474bb27af4472e2405e0",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":10,
                      "y":5},
                    "size":{
                      "width":170,
                      "height":170}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/pictures/u11.JPG"}},
{
              "id":"0ec33d90e72441c880bb5a108be05b5c",
              "label":"",
              "type":"imageBox",
              "styleType":"imageBox",
              "visible":true,
              "style":{
                "location":{
                  "x":10,
                  "y":110},
                "size":{
                  "width":170,
                  "height":65}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"e3e094f7e396426fb119923d3ab70f01",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":10,
                      "y":110},
                    "size":{
                      "width":170,
                      "height":65}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/pictures/u13.png"}},
{
              "id":"ff3b95f188194b81a2d54256b97c2cbb",
              "label":"",
              "type":"imageBox",
              "styleType":"imageBox",
              "visible":true,
              "style":{
                "location":{
                  "x":190,
                  "y":5},
                "size":{
                  "width":115,
                  "height":115}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"f8524b6c874a433c9297010f623c8879",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":190,
                      "y":5},
                    "size":{
                      "width":115,
                      "height":115}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/pictures/u15.JPG"}},
{
              "id":"4467f9ed539944a286dd1a787926a673",
              "label":"",
              "type":"imageBox",
              "styleType":"imageBox",
              "visible":true,
              "style":{
                "location":{
                  "x":190,
                  "y":125},
                "size":{
                  "width":50,
                  "height":50}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"34548d7a54164a399dfbee8e12561ce0",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":190,
                      "y":125},
                    "size":{
                      "width":50,
                      "height":50}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/pictures/u17.JPG"}},
{
              "id":"87decc4ad94e4790af327cc43e566fd2",
              "label":"",
              "type":"imageBox",
              "styleType":"imageBox",
              "visible":true,
              "style":{
                "location":{
                  "x":255,
                  "y":125},
                "size":{
                  "width":50,
                  "height":50}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"6a2aff8dbc2141b5b102763c9d9f5fc8",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":255,
                      "y":125},
                    "size":{
                      "width":50,
                      "height":50}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/pictures/u19.JPG"}},
{
              "id":"97f949b22e214ae8ad4c0e19f93fe4fa",
              "label":"",
              "type":"imageBox",
              "styleType":"imageBox",
              "visible":true,
              "style":{
                "location":{
                  "x":190,
                  "y":75},
                "size":{
                  "width":117,
                  "height":45}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"f96bee052e1d469eb4faaf048b8bbab3",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":190,
                      "y":75},
                    "size":{
                      "width":117,
                      "height":45}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/pictures/u13.png"}}],
          "data":[{
              "column0":{
                "type":"text",
                "text":"1"}},
{
              "column0":{
                "type":"text",
                "text":"2"}},
{
              "column0":{
                "type":"text",
                "text":"3"}}],
          "dataProps":["column0"]}]}},
  "masters":{
},
  "objectPaths":{
    "394d1121c6004909abe759cfce751e86":{
      "scriptId":"u0"},
    "219b7ea8754749029785c44f801afd59":{
      "scriptId":"u1"},
    "12a2e4b7ac694045a2af180729acb5d7":{
      "scriptId":"u2"},
    "29068d3a8ddb491485144c289103c2c5":{
      "scriptId":"u3"},
    "71979955f2aa41158e55a12616e61ef5":{
      "scriptId":"u4"},
    "35c174d78b5f4706ae3439ffa8d88640":{
      "scriptId":"u5"},
    "58d5db3d1366441f950edc66d7fb11aa":{
      "scriptId":"u6"},
    "b9149d3637f24786a13f16e9b99c43d6":{
      "scriptId":"u7"},
    "b46fda283e9e4923bb4bd6cbbdb39026":{
      "scriptId":"u8"},
    "cb13af9b609242b6990aa9d9f2c71b33":{
      "scriptId":"u9"},
    "f8872f336aee48e5a7d22e5728d69915":{
      "scriptId":"u10"},
    "323ec501580946e39054b91722e05e47":{
      "scriptId":"u11"},
    "58a5521fa9fb474bb27af4472e2405e0":{
      "scriptId":"u12"},
    "0ec33d90e72441c880bb5a108be05b5c":{
      "scriptId":"u13"},
    "e3e094f7e396426fb119923d3ab70f01":{
      "scriptId":"u14"},
    "ff3b95f188194b81a2d54256b97c2cbb":{
      "scriptId":"u15"},
    "f8524b6c874a433c9297010f623c8879":{
      "scriptId":"u16"},
    "4467f9ed539944a286dd1a787926a673":{
      "scriptId":"u17"},
    "34548d7a54164a399dfbee8e12561ce0":{
      "scriptId":"u18"},
    "87decc4ad94e4790af327cc43e566fd2":{
      "scriptId":"u19"},
    "6a2aff8dbc2141b5b102763c9d9f5fc8":{
      "scriptId":"u20"},
    "97f949b22e214ae8ad4c0e19f93fe4fa":{
      "scriptId":"u21"},
    "f96bee052e1d469eb4faaf048b8bbab3":{
      "scriptId":"u22"}}});