$axure.loadCurrentPage({
  "url":"微电影-2.html",
  "generationDate":new Date(1446176366543.41),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable",
"isHiden",
"isHiden2",
"text",
"separater",
"isstarted",
"isshown",
"showpicture"],
  "page":{
    "packageId":"5814ff6b68304b3e8cbd3d4b2e8f2c4e",
    "type":"Axure:Page",
    "name":"微电影-2",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"fcf4e4175cf44ddd9b986a5e31f5133d",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "disabled":true,
          "visible":true,
          "style":{
            "size":{
              "width":1348,
              "height":1200}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"2ea22f1c278340efa7ff050d30360297",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "disabled":true,
              "visible":true,
              "style":{
                "size":{
                  "width":1348,
                  "height":1200}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/home/u0.jpg"}},
{
          "id":"85a0f6086ffb4a42900cba984a2ea722",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "disabled":true,
          "visible":true,
          "style":{
            "location":{
              "x":490.5,
              "y":0},
            "size":{
              "width":385,
              "height":793},
            "borderWidth":"-1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF000000}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"9fbabf01433d4d0a9ae57c298fb8b6e3",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "disabled":true,
              "visible":true,
              "style":{
                "location":{
                  "x":490.5,
                  "y":0},
                "size":{
                  "width":385,
                  "height":793},
                "borderWidth":"-1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF000000}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/home/u2.png"}},
{
          "id":"fed21574e0af4bd9b1b8a29fb71f12f9",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":522,
              "y":173},
            "size":{
              "width":320,
              "height":507}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"9daaca12b7c24c809920efe30cf770fe",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":522,
                  "y":173},
                "size":{
                  "width":320,
                  "height":507}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/pravite/u4.png"}},
{
          "id":"7efe2a1c3b684206b05d74960fd852a6",
          "label":"框架",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFF666666},
            "location":{
              "x":522,
              "y":173},
            "size":{
              "width":320,
              "height":508},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF666666}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d92a4d332c654dc8aa5043f496c5c9b8",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFF666666},
                "location":{
                  "x":522,
                  "y":173},
                "size":{
                  "width":320,
                  "height":508},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF666666}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/微电影-1/框架_u6.png"}},
{
          "id":"394d1121c6004909abe759cfce751e86",
          "label":"状态栏",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFFF6666},
            "location":{
              "x":522,
              "y":113},
            "size":{
              "width":320,
              "height":20},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFF6666}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"219b7ea8754749029785c44f801afd59",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFF6666},
                "location":{
                  "x":522,
                  "y":113},
                "size":{
                  "width":320,
                  "height":20},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFF6666}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/home/状态栏_u31.png"}},
{
          "id":"12a2e4b7ac694045a2af180729acb5d7",
          "label":"框架",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Charlemagne Std Bold', 'Charlemagne Std'",
            "fontSize":"14px",
            "fontWeight":"700",
            "lineSpacing":"20px",
            "fill":{
              "fillType":"solid",
              "color":0xFFFF6666},
            "location":{
              "x":522,
              "y":133},
            "size":{
              "width":320,
              "height":40},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFF6666}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"29068d3a8ddb491485144c289103c2c5",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Charlemagne Std Bold', 'Charlemagne Std'",
                "fontSize":"14px",
                "fontWeight":"700",
                "lineSpacing":"20px",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFF6666},
                "location":{
                  "x":522,
                  "y":133},
                "size":{
                  "width":320,
                  "height":40},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFF6666}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/home/框架_u33.png"}},
{
          "id":"71979955f2aa41158e55a12616e61ef5",
          "label":"消息",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":532,
              "y":143},
            "size":{
              "width":25,
              "height":25}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"35c174d78b5f4706ae3439ffa8d88640",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":532,
                  "y":143},
                "size":{
                  "width":25,
                  "height":25}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 Home",
                      "target":{
                        "targetType":"page",
                        "url":"home.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/pravite/消息_u44.png"}},
{
          "id":"58d5db3d1366441f950edc66d7fb11aa",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "fontSize":"20px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "location":{
              "x":622,
              "y":139},
            "size":{
              "width":121,
              "height":27}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b9149d3637f24786a13f16e9b99c43d6",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "fontSize":"20px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "location":{
                  "x":622,
                  "y":139},
                "size":{
                  "width":121,
                  "height":27}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"66d1b0d1387446bcb9c58f37355f7637",
          "label":"mylocation",
          "type":"dynamicPanel",
          "styleType":"dynamicPanel",
          "visible":true,
          "style":{
            "location":{
              "x":522,
              "y":193},
            "size":{
              "width":320,
              "height":488}},
          "adaptiveStyles":{
},
          "interactionMap":{
            "onDrag":{
              "description":"OnDrag",
              "cases":[{
                  "description":"用例 1<br> (If &quot;[[DragX]]&quot; &gt; &quot;0&quot;)",
                  "isNewIfGroup":false,
                  "condition":{
                    "exprType":"binaryOp",
                    "op":">",
                    "leftExpr":{
                      "exprType":"stringLiteral",
                      "value":"[[DragX]]",
                      "localVariables":{
},
                      "stos":[{
                          "sto":"var",
                          "name":"dragx"}]},
                    "rightExpr":{
                      "exprType":"stringLiteral",
                      "value":"0",
                      "stos":[]}},
                  "actions":[{
                      "action":"moveWidget",
                      "description":"移动 (图片) x 轴拖动,<br>(图片) x 轴拖动,<br>(图片) x 轴拖动,<br>(形状) x 轴拖动,<br>(图片) x 轴拖动,<br>(形状) x 轴拖动,<br>(图片) x 轴拖动,<br>(形状) x 轴拖动,<br>(图片) x 轴拖动",
                      "objectsToMoves":[{
                          "objectPath":["d3d40ba90a6549ab9e731eac20687d9b"],
                          "moveInfo":{
                            "moveType":"dragX",
                            "xValue":{
                              "exprType":"stringLiteral",
                              "value":"0",
                              "stos":[]},
                            "yValue":{
                              "exprType":"stringLiteral",
                              "value":"0",
                              "stos":[]},
                            "options":{
}}},
{
                          "objectPath":["1befea9c84d44765bc3bc3a474cc8f8a"],
                          "moveInfo":{
                            "moveType":"dragX",
                            "xValue":{
                              "exprType":"stringLiteral",
                              "value":"0",
                              "stos":[]},
                            "yValue":{
                              "exprType":"stringLiteral",
                              "value":"0",
                              "stos":[]},
                            "options":{
}}},
{
                          "objectPath":["4c0f3d2909b549cabb9cd55bfbd18e91"],
                          "moveInfo":{
                            "moveType":"dragX",
                            "xValue":{
                              "exprType":"stringLiteral",
                              "value":"0",
                              "stos":[]},
                            "yValue":{
                              "exprType":"stringLiteral",
                              "value":"0",
                              "stos":[]},
                            "options":{
}}},
{
                          "objectPath":["79d0f64fc9d04348bf277488142ac63c"],
                          "moveInfo":{
                            "moveType":"dragX",
                            "xValue":{
                              "exprType":"stringLiteral",
                              "value":"0",
                              "stos":[]},
                            "yValue":{
                              "exprType":"stringLiteral",
                              "value":"0",
                              "stos":[]},
                            "options":{
}}},
{
                          "objectPath":["9d8dc00ed13440059c8ce6c0f39ed2d6"],
                          "moveInfo":{
                            "moveType":"dragX",
                            "xValue":{
                              "exprType":"stringLiteral",
                              "value":"0",
                              "stos":[]},
                            "yValue":{
                              "exprType":"stringLiteral",
                              "value":"0",
                              "stos":[]},
                            "options":{
}}},
{
                          "objectPath":["66e729175293401394392aa12094abc6"],
                          "moveInfo":{
                            "moveType":"dragX",
                            "xValue":{
                              "exprType":"stringLiteral",
                              "value":"0",
                              "stos":[]},
                            "yValue":{
                              "exprType":"stringLiteral",
                              "value":"0",
                              "stos":[]},
                            "options":{
}}},
{
                          "objectPath":["d3aeb06ccfb2449bbe4f0bb70e497c95"],
                          "moveInfo":{
                            "moveType":"dragX",
                            "xValue":{
                              "exprType":"stringLiteral",
                              "value":"0",
                              "stos":[]},
                            "yValue":{
                              "exprType":"stringLiteral",
                              "value":"0",
                              "stos":[]},
                            "options":{
}}},
{
                          "objectPath":["6346e9cafb7440ffad3f517f9f7ea5c2"],
                          "moveInfo":{
                            "moveType":"dragX",
                            "xValue":{
                              "exprType":"stringLiteral",
                              "value":"0",
                              "stos":[]},
                            "yValue":{
                              "exprType":"stringLiteral",
                              "value":"0",
                              "stos":[]},
                            "options":{
}}},
{
                          "objectPath":["0262cd9c277244c39afcf7427ed280ea"],
                          "moveInfo":{
                            "moveType":"dragX",
                            "xValue":{
                              "exprType":"stringLiteral",
                              "value":"0",
                              "stos":[]},
                            "yValue":{
                              "exprType":"stringLiteral",
                              "value":"0",
                              "stos":[]},
                            "options":{
}}}]}]},
{
                  "description":"用例 2<br> (Else If &quot;[[DragX]]&quot; &lt; &quot;0&quot;)",
                  "isNewIfGroup":false,
                  "condition":{
                    "exprType":"binaryOp",
                    "op":"<",
                    "leftExpr":{
                      "exprType":"stringLiteral",
                      "value":"[[DragX]]",
                      "localVariables":{
},
                      "stos":[{
                          "sto":"var",
                          "name":"dragx"}]},
                    "rightExpr":{
                      "exprType":"stringLiteral",
                      "value":"0",
                      "stos":[]}},
                  "actions":[{
                      "action":"moveWidget",
                      "description":"移动 (图片) x 轴拖动,<br>(图片) x 轴拖动,<br>(图片) x 轴拖动,<br>(图片) x 轴拖动,<br>(图片) x 轴拖动,<br>(形状) x 轴拖动,<br>(形状) x 轴拖动,<br>(形状) x 轴拖动,<br>(图片) x 轴拖动",
                      "objectsToMoves":[{
                          "objectPath":["d3d40ba90a6549ab9e731eac20687d9b"],
                          "moveInfo":{
                            "moveType":"dragX",
                            "xValue":{
                              "exprType":"stringLiteral",
                              "value":"0",
                              "stos":[]},
                            "yValue":{
                              "exprType":"stringLiteral",
                              "value":"0",
                              "stos":[]},
                            "options":{
}}},
{
                          "objectPath":["1befea9c84d44765bc3bc3a474cc8f8a"],
                          "moveInfo":{
                            "moveType":"dragX",
                            "xValue":{
                              "exprType":"stringLiteral",
                              "value":"0",
                              "stos":[]},
                            "yValue":{
                              "exprType":"stringLiteral",
                              "value":"0",
                              "stos":[]},
                            "options":{
}}},
{
                          "objectPath":["4c0f3d2909b549cabb9cd55bfbd18e91"],
                          "moveInfo":{
                            "moveType":"dragX",
                            "xValue":{
                              "exprType":"stringLiteral",
                              "value":"0",
                              "stos":[]},
                            "yValue":{
                              "exprType":"stringLiteral",
                              "value":"0",
                              "stos":[]},
                            "options":{
}}},
{
                          "objectPath":["9d8dc00ed13440059c8ce6c0f39ed2d6"],
                          "moveInfo":{
                            "moveType":"dragX",
                            "xValue":{
                              "exprType":"stringLiteral",
                              "value":"0",
                              "stos":[]},
                            "yValue":{
                              "exprType":"stringLiteral",
                              "value":"0",
                              "stos":[]},
                            "options":{
}}},
{
                          "objectPath":["d3aeb06ccfb2449bbe4f0bb70e497c95"],
                          "moveInfo":{
                            "moveType":"dragX",
                            "xValue":{
                              "exprType":"stringLiteral",
                              "value":"0",
                              "stos":[]},
                            "yValue":{
                              "exprType":"stringLiteral",
                              "value":"0",
                              "stos":[]},
                            "options":{
}}},
{
                          "objectPath":["66e729175293401394392aa12094abc6"],
                          "moveInfo":{
                            "moveType":"dragX",
                            "xValue":{
                              "exprType":"stringLiteral",
                              "value":"0",
                              "stos":[]},
                            "yValue":{
                              "exprType":"stringLiteral",
                              "value":"0",
                              "stos":[]},
                            "options":{
}}},
{
                          "objectPath":["79d0f64fc9d04348bf277488142ac63c"],
                          "moveInfo":{
                            "moveType":"dragX",
                            "xValue":{
                              "exprType":"stringLiteral",
                              "value":"0",
                              "stos":[]},
                            "yValue":{
                              "exprType":"stringLiteral",
                              "value":"0",
                              "stos":[]},
                            "options":{
}}},
{
                          "objectPath":["6346e9cafb7440ffad3f517f9f7ea5c2"],
                          "moveInfo":{
                            "moveType":"dragX",
                            "xValue":{
                              "exprType":"stringLiteral",
                              "value":"0",
                              "stos":[]},
                            "yValue":{
                              "exprType":"stringLiteral",
                              "value":"0",
                              "stos":[]},
                            "options":{
}}},
{
                          "objectPath":["0262cd9c277244c39afcf7427ed280ea"],
                          "moveInfo":{
                            "moveType":"dragX",
                            "xValue":{
                              "exprType":"stringLiteral",
                              "value":"0",
                              "stos":[]},
                            "yValue":{
                              "exprType":"stringLiteral",
                              "value":"0",
                              "stos":[]},
                            "options":{
}}}]}]}]}},
          "scrollbars":"none",
          "fitToContent":false,
          "propagate":false,
          "diagrams":[{
              "id":"c2535b09711749e481401c7d017e0a3e",
              "label":"State1",
              "type":"Axure:PanelDiagram",
              "objects":[{
                  "id":"4c0f3d2909b549cabb9cd55bfbd18e91",
                  "label":"",
                  "parentDynamicPanel":"66d1b0d1387446bcb9c58f37355f7637",
                  "type":"imageBox",
                  "styleType":"imageBox",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":-320,
                      "y":0},
                    "size":{
                      "width":320,
                      "height":320}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"729e2a6e29014155985f93b3c525befc",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"66d1b0d1387446bcb9c58f37355f7637",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":-320,
                          "y":0},
                        "size":{
                          "width":320,
                          "height":320}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/微电影-1/u17.png"}},
{
                  "id":"1befea9c84d44765bc3bc3a474cc8f8a",
                  "label":"",
                  "parentDynamicPanel":"66d1b0d1387446bcb9c58f37355f7637",
                  "type":"imageBox",
                  "styleType":"imageBox",
                  "visible":true,
                  "style":{
                    "size":{
                      "width":320,
                      "height":320}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"9045a076b2aa42d9a72072bee4ea09d0",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"66d1b0d1387446bcb9c58f37355f7637",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "size":{
                          "width":320,
                          "height":320}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/home/u83.JPG"}},
{
                  "id":"d3d40ba90a6549ab9e731eac20687d9b",
                  "label":"",
                  "parentDynamicPanel":"66d1b0d1387446bcb9c58f37355f7637",
                  "type":"imageBox",
                  "styleType":"imageBox",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":320,
                      "y":0},
                    "size":{
                      "width":320,
                      "height":320}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"913def01531a47f1a0ebb52f822334bf",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"66d1b0d1387446bcb9c58f37355f7637",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":320,
                          "y":0},
                        "size":{
                          "width":320,
                          "height":320}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/home/u85.JPG"}},
{
                  "id":"79d0f64fc9d04348bf277488142ac63c",
                  "label":"",
                  "parentDynamicPanel":"66d1b0d1387446bcb9c58f37355f7637",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFFFFFFFF,
                      "opacity":1},
                    "location":{
                      "x":21,
                      "y":368},
                    "size":{
                      "width":278,
                      "height":32}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"3a58024834f8428d8693825d5b867bfb",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"66d1b0d1387446bcb9c58f37355f7637",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFFFFFFFF,
                          "opacity":1},
                        "location":{
                          "x":21,
                          "y":368},
                        "size":{
                          "width":278,
                          "height":32}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"9d8dc00ed13440059c8ce6c0f39ed2d6",
                  "label":"",
                  "parentDynamicPanel":"66d1b0d1387446bcb9c58f37355f7637",
                  "type":"imageBox",
                  "styleType":"imageBox",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":135,
                      "y":440},
                    "size":{
                      "width":175,
                      "height":27}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"faa20ce2343349929afb73bd989d479c",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"66d1b0d1387446bcb9c58f37355f7637",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":135,
                          "y":440},
                        "size":{
                          "width":175,
                          "height":27}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/微电影-1/u25.png"}},
{
                  "id":"66e729175293401394392aa12094abc6",
                  "label":"",
                  "parentDynamicPanel":"66d1b0d1387446bcb9c58f37355f7637",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFFFFFFFF,
                      "opacity":1},
                    "location":{
                      "x":-312,
                      "y":350},
                    "size":{
                      "width":290,
                      "height":96}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"4fafe163af6b40dd92c3307c88893ee9",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"66d1b0d1387446bcb9c58f37355f7637",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFFFFFFFF,
                          "opacity":1},
                        "location":{
                          "x":-312,
                          "y":350},
                        "size":{
                          "width":290,
                          "height":96}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"d3aeb06ccfb2449bbe4f0bb70e497c95",
                  "label":"",
                  "parentDynamicPanel":"66d1b0d1387446bcb9c58f37355f7637",
                  "type":"imageBox",
                  "styleType":"imageBox",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":-182,
                      "y":456},
                    "size":{
                      "width":175,
                      "height":27}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"93fc0004f8c84191a98fe98686acfd19",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"66d1b0d1387446bcb9c58f37355f7637",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":-182,
                          "y":456},
                        "size":{
                          "width":175,
                          "height":27}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/微电影-1/u25.png"}},
{
                  "id":"6346e9cafb7440ffad3f517f9f7ea5c2",
                  "label":"",
                  "parentDynamicPanel":"66d1b0d1387446bcb9c58f37355f7637",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFFFFFFFF,
                      "opacity":1},
                    "location":{
                      "x":338,
                      "y":350},
                    "size":{
                      "width":290,
                      "height":96}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"c22f0effb30e4aea8206c219d1360939",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"66d1b0d1387446bcb9c58f37355f7637",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFFFFFFFF,
                          "opacity":1},
                        "location":{
                          "x":338,
                          "y":350},
                        "size":{
                          "width":290,
                          "height":96}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"0262cd9c277244c39afcf7427ed280ea",
                  "label":"",
                  "parentDynamicPanel":"66d1b0d1387446bcb9c58f37355f7637",
                  "type":"imageBox",
                  "styleType":"imageBox",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":468,
                      "y":456},
                    "size":{
                      "width":175,
                      "height":27}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"7d72f97916504d8bb04368815c114a18",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"66d1b0d1387446bcb9c58f37355f7637",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":468,
                          "y":456},
                        "size":{
                          "width":175,
                          "height":27}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/微电影-1/u25.png"}}]}]},
{
          "id":"dc0d88c42cd54d318923dfc2cef85657",
          "label":"评论",
          "type":"textBox",
          "styleType":"textBox",
          "visible":false,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF999999,
              "opacity":1},
            "location":{
              "x":533,
              "y":518},
            "size":{
              "width":269,
              "height":25},
            "visible":false},
          "adaptiveStyles":{
},
          "submitButton":{
            "path":[],
            "id":"4412ecc4c63648e0bc5d3c16473dbaf4"},
          "placeholderText":"@xx"},
{
          "id":"733bcea0904f4d4489ae1a47e6839abb",
          "label":"like",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFFFFF},
            "location":{
              "x":712,
              "y":629},
            "size":{
              "width":60,
              "height":30},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF},
            "cornerRadiusTopLeft":"5"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c143c0a5d71a4da88c8c4f689b5fe227",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "location":{
                  "x":712,
                  "y":629},
                "size":{
                  "width":60,
                  "height":30},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "cornerRadiusTopLeft":"5"},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"fadeWidget",
                      "description":"切换 like",
                      "objectsToFades":[{
                          "objectPath":["2cd5049f8c424d17bda52d977acb2e5d"],
                          "fadeInfo":{
                            "fadeType":"toggle",
                            "options":{
                              "showType":"none"}}}]}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"2cd5049f8c424d17bda52d977acb2e5d",
          "label":"like",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":false,
          "style":{
            "location":{
              "x":702,
              "y":633},
            "size":{
              "width":29,
              "height":26},
            "visible":false},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a142d21397ce40b8a2a6c0c63e5a2736",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":false,
              "style":{
                "location":{
                  "x":702,
                  "y":633},
                "size":{
                  "width":29,
                  "height":26},
                "visible":false},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/微电影-1/like_u38.png"}},
{
          "id":"4412ecc4c63648e0bc5d3c16473dbaf4",
          "label":"评论",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFFFFF},
            "location":{
              "x":772,
              "y":629},
            "size":{
              "width":60,
              "height":30},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF},
            "cornerRadiusTopLeft":"5"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f9919663d39941a5a982aaedb9eddfb9",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "location":{
                  "x":772,
                  "y":629},
                "size":{
                  "width":60,
                  "height":30},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "cornerRadiusTopLeft":"5"},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"fadeWidget",
                      "description":"切换 评论",
                      "objectsToFades":[{
                          "objectPath":["dc0d88c42cd54d318923dfc2cef85657"],
                          "fadeInfo":{
                            "fadeType":"toggle",
                            "options":{
                              "showType":"none"}}}]}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"4486165fa4b649588614ced111a0de4b",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":532,
              "y":201},
            "size":{
              "width":40,
              "height":40}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"57131f1eaf354d168e7a0cf922bf7fb1",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":532,
                  "y":201},
                "size":{
                  "width":40,
                  "height":40}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/微电影-1/u42.png"}}]}},
  "masters":{
},
  "objectPaths":{
    "fcf4e4175cf44ddd9b986a5e31f5133d":{
      "scriptId":"u0"},
    "2ea22f1c278340efa7ff050d30360297":{
      "scriptId":"u1"},
    "85a0f6086ffb4a42900cba984a2ea722":{
      "scriptId":"u2"},
    "9fbabf01433d4d0a9ae57c298fb8b6e3":{
      "scriptId":"u3"},
    "fed21574e0af4bd9b1b8a29fb71f12f9":{
      "scriptId":"u4"},
    "9daaca12b7c24c809920efe30cf770fe":{
      "scriptId":"u5"},
    "7efe2a1c3b684206b05d74960fd852a6":{
      "scriptId":"u6"},
    "d92a4d332c654dc8aa5043f496c5c9b8":{
      "scriptId":"u7"},
    "394d1121c6004909abe759cfce751e86":{
      "scriptId":"u8"},
    "219b7ea8754749029785c44f801afd59":{
      "scriptId":"u9"},
    "12a2e4b7ac694045a2af180729acb5d7":{
      "scriptId":"u10"},
    "29068d3a8ddb491485144c289103c2c5":{
      "scriptId":"u11"},
    "71979955f2aa41158e55a12616e61ef5":{
      "scriptId":"u12"},
    "35c174d78b5f4706ae3439ffa8d88640":{
      "scriptId":"u13"},
    "58d5db3d1366441f950edc66d7fb11aa":{
      "scriptId":"u14"},
    "b9149d3637f24786a13f16e9b99c43d6":{
      "scriptId":"u15"},
    "66d1b0d1387446bcb9c58f37355f7637":{
      "scriptId":"u16"},
    "4c0f3d2909b549cabb9cd55bfbd18e91":{
      "scriptId":"u17"},
    "729e2a6e29014155985f93b3c525befc":{
      "scriptId":"u18"},
    "1befea9c84d44765bc3bc3a474cc8f8a":{
      "scriptId":"u19"},
    "9045a076b2aa42d9a72072bee4ea09d0":{
      "scriptId":"u20"},
    "d3d40ba90a6549ab9e731eac20687d9b":{
      "scriptId":"u21"},
    "913def01531a47f1a0ebb52f822334bf":{
      "scriptId":"u22"},
    "79d0f64fc9d04348bf277488142ac63c":{
      "scriptId":"u23"},
    "3a58024834f8428d8693825d5b867bfb":{
      "scriptId":"u24"},
    "9d8dc00ed13440059c8ce6c0f39ed2d6":{
      "scriptId":"u25"},
    "faa20ce2343349929afb73bd989d479c":{
      "scriptId":"u26"},
    "66e729175293401394392aa12094abc6":{
      "scriptId":"u27"},
    "4fafe163af6b40dd92c3307c88893ee9":{
      "scriptId":"u28"},
    "d3aeb06ccfb2449bbe4f0bb70e497c95":{
      "scriptId":"u29"},
    "93fc0004f8c84191a98fe98686acfd19":{
      "scriptId":"u30"},
    "6346e9cafb7440ffad3f517f9f7ea5c2":{
      "scriptId":"u31"},
    "c22f0effb30e4aea8206c219d1360939":{
      "scriptId":"u32"},
    "0262cd9c277244c39afcf7427ed280ea":{
      "scriptId":"u33"},
    "7d72f97916504d8bb04368815c114a18":{
      "scriptId":"u34"},
    "dc0d88c42cd54d318923dfc2cef85657":{
      "scriptId":"u35"},
    "733bcea0904f4d4489ae1a47e6839abb":{
      "scriptId":"u36"},
    "c143c0a5d71a4da88c8c4f689b5fe227":{
      "scriptId":"u37"},
    "2cd5049f8c424d17bda52d977acb2e5d":{
      "scriptId":"u38"},
    "a142d21397ce40b8a2a6c0c63e5a2736":{
      "scriptId":"u39"},
    "4412ecc4c63648e0bc5d3c16473dbaf4":{
      "scriptId":"u40"},
    "f9919663d39941a5a982aaedb9eddfb9":{
      "scriptId":"u41"},
    "4486165fa4b649588614ced111a0de4b":{
      "scriptId":"u42"},
    "57131f1eaf354d168e7a0cf922bf7fb1":{
      "scriptId":"u43"}}});