$axure.loadCurrentPage({
  "url":"comments.html",
  "generationDate":new Date(1446176365690.01),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable",
"isHiden",
"isHiden2",
"text",
"separater",
"isstarted",
"isshown",
"showpicture"],
  "page":{
    "packageId":"dbce30b119b442209d36e53cab5b1478",
    "type":"Axure:Page",
    "name":"comments",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"89020cef965e416b975765f21840e166",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "disabled":true,
          "visible":true,
          "style":{
            "size":{
              "width":1348,
              "height":1200}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e479dcbbe4774a72b49421dc5a2453e2",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "disabled":true,
              "visible":true,
              "style":{
                "size":{
                  "width":1348,
                  "height":1200}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/home/u0.jpg"}},
{
          "id":"35e91124b43e4824887aef9a5ad2e610",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "disabled":true,
          "visible":true,
          "style":{
            "location":{
              "x":490.5,
              "y":0},
            "size":{
              "width":385,
              "height":793},
            "borderWidth":"-1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF000000}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a0fd0a1cacfe4ed29e55c17c52336a79",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "disabled":true,
              "visible":true,
              "style":{
                "location":{
                  "x":490.5,
                  "y":0},
                "size":{
                  "width":385,
                  "height":793},
                "borderWidth":"-1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF000000}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/home/u2.png"}},
{
          "id":"66f8ecbe844e421aaf7e23645bf56b93",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":522,
              "y":173},
            "size":{
              "width":320,
              "height":507}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"3a615136d8624ff28623f04f9afc4b06",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":522,
                  "y":173},
                "size":{
                  "width":320,
                  "height":507}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/pravite/u4.png"}},
{
          "id":"a311b622ca534622a2b42dcfb8b56be2",
          "label":"状态栏",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFFF6666},
            "location":{
              "x":522,
              "y":113},
            "size":{
              "width":320,
              "height":20},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFF6666}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a10b13b3023e45cc85e0df89fe46d2a4",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFF6666},
                "location":{
                  "x":522,
                  "y":113},
                "size":{
                  "width":320,
                  "height":20},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFF6666}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/home/状态栏_u31.png"}},
{
          "id":"d4680cafb64e4793b88aeba1cf00d9b1",
          "label":"框架",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Charlemagne Std Bold', 'Charlemagne Std'",
            "fontSize":"14px",
            "fontWeight":"700",
            "lineSpacing":"20px",
            "fill":{
              "fillType":"solid",
              "color":0xFFFF6666},
            "location":{
              "x":522,
              "y":133},
            "size":{
              "width":320,
              "height":40},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFF6666}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c3b8047ad6094711931d1fc820e6beba",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Charlemagne Std Bold', 'Charlemagne Std'",
                "fontSize":"14px",
                "fontWeight":"700",
                "lineSpacing":"20px",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFF6666},
                "location":{
                  "x":522,
                  "y":133},
                "size":{
                  "width":320,
                  "height":40},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFF6666}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/home/框架_u33.png"}},
{
          "id":"896afdf4b89b436d801bf8201f36a1ba",
          "label":"框架",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFF666666},
            "location":{
              "x":522,
              "y":545},
            "size":{
              "width":320,
              "height":136},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF666666}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"52ad66779e874785ae38bc94f5062fa1",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFF666666},
                "location":{
                  "x":522,
                  "y":545},
                "size":{
                  "width":320,
                  "height":136},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF666666}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/comments/框架_u10.png"}},
{
          "id":"794d9d0f77204c0fb683178da76482b0",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "fontSize":"20px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "location":{
              "x":642,
              "y":139},
            "size":{
              "width":81,
              "height":27}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"0605509805d0416b9313edadb9a7006f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "fontSize":"20px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "location":{
                  "x":642,
                  "y":139},
                "size":{
                  "width":81,
                  "height":27}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"794f6fe94cc842b792d3084b84ea14e3",
          "label":"",
          "type":"repeater",
          "styleType":"repeater",
          "visible":true,
          "style":{
            "location":{
              "x":522,
              "y":443},
            "size":{
              "width":250,
              "height":150}},
          "adaptiveStyles":{
},
          "interactionMap":{
            "onItemLoad":{
              "description":"OnItemLoad",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"setFunction",
                      "description":"设置 文字于 (形状) = &quot;[[Item.Column0]]&quot;",
                      "expr":{
                        "exprType":"block",
                        "subExprs":[{
                            "exprType":"fcall",
                            "functionName":"SetWidgetRichText",
                            "arguments":[{
                                "exprType":"pathLiteral",
                                "isThis":false,
                                "isFocused":false,
                                "isTarget":false,
                                "value":["23c63f24d56449e990d4f4444093a79f"]},
{
                                "exprType":"stringLiteral",
                                "value":"[[Item.Column0]]",
                                "localVariables":{
},
                                "stos":[{
                                    "sto":"item",
                                    "name":"column0",
                                    "isTarget":false}]},
{
                                "exprType":"booleanLiteral",
                                "value":true}]}]}}]}]}},
          "repeaterPropMap":{
            "isolateRadio":true,
            "isolateSelection":true,
            "default":{
              "loadLocalDefault":true,
              "wrap":-1,
              "vertical":true,
              "horizontalSpacing":0,
              "verticalSpacing":0,
              "hasAltColor":false,
              "itemsPerPage":-1,
              "currPage":1,
              "backColor":{
                "r":255,
                "g":255,
                "b":255,
                "a":0},
              "altColor":{
                "r":255,
                "g":255,
                "b":255,
                "a":0}},
            "":{
              "width":320,
              "height":40,
              "loadLocalDefault":true,
              "wrap":-1,
              "vertical":true,
              "horizontalSpacing":0,
              "verticalSpacing":0,
              "hasAltColor":false,
              "itemsPerPage":-1,
              "currPage":1,
              "backColor":{
                "r":255,
                "g":255,
                "b":255,
                "a":0},
              "altColor":{
                "r":255,
                "g":255,
                "b":255,
                "a":0}}},
          "objects":[{
              "id":"6b0261d5851546a19167261e40c6ae15",
              "label":"",
              "type":"buttonShape",
              "styleType":"buttonShape",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFFCC},
                "size":{
                  "width":320,
                  "height":40}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"23c63f24d56449e990d4f4444093a79f",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFFFFFCC},
                    "size":{
                      "width":320,
                      "height":40}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/comments/u15.png"}},
{
              "id":"8a869a36d55d40b2af731f78f07e6523",
              "label":"",
              "type":"horizontalLine",
              "styleType":"horizontalLine",
              "visible":true,
              "style":{
                "location":{
                  "x":0,
                  "y":30},
                "size":{
                  "width":320,
                  "height":10},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF333333}},
              "adaptiveStyles":{
},
              "images":{
                "start~":"resources/images/transparent.gif",
                "end~":"resources/images/transparent.gif",
                "line~":"images/comments/u17_line.png"}}],
          "data":[{
              "column0":{
                "type":"text",
                "text":"1"}},
{
              "column0":{
                "type":"text",
                "text":"2"}},
{
              "column0":{
                "type":"text",
                "text":"3"}}],
          "dataProps":["column0"]},
{
          "id":"5ccc235c39f646bd96fe01d2834407f2",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFFFFFCC},
            "location":{
              "x":522,
              "y":173},
            "size":{
              "width":320,
              "height":162}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"37be3693cf974871a9038a8b6c050fd4",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFFCC},
                "location":{
                  "x":522,
                  "y":173},
                "size":{
                  "width":320,
                  "height":162}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/comments/u18.png"}},
{
          "id":"52fefa39e0d742fc8d9e984053b12a57",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":522,
              "y":209},
            "size":{
              "width":320,
              "height":10},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF797979}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/search/u11_line.png"}},
{
          "id":"bb7bbe9d99e641819de7e9a2e3f53a86",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":522,
              "y":243},
            "size":{
              "width":320,
              "height":10},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF797979}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/search/u11_line.png"}},
{
          "id":"cf8fe054777840e1a686a497074edb85",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":522,
              "y":283},
            "size":{
              "width":320,
              "height":10},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF797979}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/search/u11_line.png"}},
{
          "id":"fd2ea2b4a8034c7692c3fd5b983d66c4",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":542,
              "y":183},
            "size":{
              "width":300,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"0e0ba34a26694ccb8f7e3374a09eb798",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":542,
                  "y":183},
                "size":{
                  "width":300,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"7a925e5e1f174b5b98f49ff771727343",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":762,
              "y":173},
            "size":{
              "width":80,
              "height":75}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d7856c43aee74e24bfc6d2d114ab6e31",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":762,
                  "y":173},
                "size":{
                  "width":80,
                  "height":75}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/home/u50.JPG"}},
{
          "id":"3db35c80716641f2bca2e33d7ce7f5bc",
          "label":"",
          "type":"repeater",
          "styleType":"repeater",
          "visible":true,
          "style":{
            "location":{
              "x":522,
              "y":323},
            "size":{
              "width":250,
              "height":150}},
          "adaptiveStyles":{
},
          "interactionMap":{
            "onItemLoad":{
              "description":"OnItemLoad",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"setFunction",
                      "description":"设置 文字于 (形状) = &quot;[[Item.Column0]]&quot;",
                      "expr":{
                        "exprType":"block",
                        "subExprs":[{
                            "exprType":"fcall",
                            "functionName":"SetWidgetRichText",
                            "arguments":[{
                                "exprType":"pathLiteral",
                                "isThis":false,
                                "isFocused":false,
                                "isTarget":false,
                                "value":["1302eb291dc24863b1e806b65410488f"]},
{
                                "exprType":"stringLiteral",
                                "value":"[[Item.Column0]]",
                                "localVariables":{
},
                                "stos":[{
                                    "sto":"item",
                                    "name":"column0",
                                    "isTarget":false}]},
{
                                "exprType":"booleanLiteral",
                                "value":true}]}]}}]}]}},
          "repeaterPropMap":{
            "isolateRadio":true,
            "isolateSelection":true,
            "default":{
              "loadLocalDefault":true,
              "wrap":-1,
              "vertical":true,
              "horizontalSpacing":0,
              "verticalSpacing":0,
              "hasAltColor":false,
              "itemsPerPage":-1,
              "currPage":1,
              "backColor":{
                "r":255,
                "g":255,
                "b":255,
                "a":0},
              "altColor":{
                "r":255,
                "g":255,
                "b":255,
                "a":0}},
            "":{
              "width":320,
              "height":40,
              "loadLocalDefault":true,
              "wrap":-1,
              "vertical":true,
              "horizontalSpacing":0,
              "verticalSpacing":0,
              "hasAltColor":false,
              "itemsPerPage":-1,
              "currPage":1,
              "backColor":{
                "r":255,
                "g":255,
                "b":255,
                "a":0},
              "altColor":{
                "r":255,
                "g":255,
                "b":255,
                "a":0}}},
          "objects":[{
              "id":"215ae78d54a94ba59deb4330df8dc0fc",
              "label":"",
              "type":"buttonShape",
              "styleType":"buttonShape",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFFCC},
                "size":{
                  "width":320,
                  "height":40}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"1302eb291dc24863b1e806b65410488f",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFFFFFCC},
                    "size":{
                      "width":320,
                      "height":40}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/comments/u15.png"}},
{
              "id":"342bd51fdc304cdd889844c20b6cc0c2",
              "label":"",
              "type":"horizontalLine",
              "styleType":"horizontalLine",
              "visible":true,
              "style":{
                "location":{
                  "x":0,
                  "y":30},
                "size":{
                  "width":320,
                  "height":10},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF333333}},
              "adaptiveStyles":{
},
              "images":{
                "start~":"resources/images/transparent.gif",
                "end~":"resources/images/transparent.gif",
                "line~":"images/comments/u17_line.png"}}],
          "data":[{
              "column0":{
                "type":"text",
                "text":"1"}},
{
              "column0":{
                "type":"text",
                "text":"2"}},
{
              "column0":{
                "type":"text",
                "text":"3"}}],
          "dataProps":["column0"]},
{
          "id":"e01d8fddfe0243a5a9e402a4565052fc",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":532,
              "y":173},
            "size":{
              "width":40,
              "height":40}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e1697d9a0772419da23462b1332c6cd3",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":532,
                  "y":173},
                "size":{
                  "width":40,
                  "height":40}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/comments/u31.png"}},
{
          "id":"bf38318186334d3bbe4d81b634336cc4",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":582,
              "y":193},
            "size":{
              "width":130,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"41d47c7766374d91a86fa95d75684f39",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":582,
                  "y":193},
                "size":{
                  "width":130,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"9edfdc64e36b422ba5061af3ad0bb34b",
          "label":"",
          "type":"repeater",
          "styleType":"repeater",
          "visible":true,
          "style":{
            "location":{
              "x":522,
              "y":561},
            "size":{
              "width":250,
              "height":150}},
          "adaptiveStyles":{
},
          "interactionMap":{
            "onItemLoad":{
              "description":"OnItemLoad",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"setFunction",
                      "description":"设置 文字于 (形状) = &quot;[[Item.Column0]]&quot;",
                      "expr":{
                        "exprType":"block",
                        "subExprs":[{
                            "exprType":"fcall",
                            "functionName":"SetWidgetRichText",
                            "arguments":[{
                                "exprType":"pathLiteral",
                                "isThis":false,
                                "isFocused":false,
                                "isTarget":false,
                                "value":["780d9e402b864882a56fbef3e97d4000"]},
{
                                "exprType":"stringLiteral",
                                "value":"[[Item.Column0]]",
                                "localVariables":{
},
                                "stos":[{
                                    "sto":"item",
                                    "name":"column0",
                                    "isTarget":false}]},
{
                                "exprType":"booleanLiteral",
                                "value":true}]}]}}]}]}},
          "repeaterPropMap":{
            "isolateRadio":true,
            "isolateSelection":true,
            "default":{
              "loadLocalDefault":true,
              "wrap":-1,
              "vertical":true,
              "horizontalSpacing":0,
              "verticalSpacing":0,
              "hasAltColor":false,
              "itemsPerPage":-1,
              "currPage":1,
              "backColor":{
                "r":255,
                "g":255,
                "b":255,
                "a":0},
              "altColor":{
                "r":255,
                "g":255,
                "b":255,
                "a":0}},
            "":{
              "width":320,
              "height":40,
              "loadLocalDefault":true,
              "wrap":-1,
              "vertical":true,
              "horizontalSpacing":0,
              "verticalSpacing":0,
              "hasAltColor":false,
              "itemsPerPage":-1,
              "currPage":1,
              "backColor":{
                "r":255,
                "g":255,
                "b":255,
                "a":0},
              "altColor":{
                "r":255,
                "g":255,
                "b":255,
                "a":0}}},
          "objects":[{
              "id":"5ee02480243b45abb84e50943dc31eaa",
              "label":"",
              "type":"buttonShape",
              "styleType":"buttonShape",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFFCC},
                "size":{
                  "width":320,
                  "height":40}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"780d9e402b864882a56fbef3e97d4000",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFFFFFCC},
                    "size":{
                      "width":320,
                      "height":40}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/comments/u15.png"}},
{
              "id":"78adbbbd480c4afda57e11ea8f327acb",
              "label":"",
              "type":"horizontalLine",
              "styleType":"horizontalLine",
              "visible":true,
              "style":{
                "location":{
                  "x":0,
                  "y":30},
                "size":{
                  "width":320,
                  "height":10},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF333333}},
              "adaptiveStyles":{
},
              "images":{
                "start~":"resources/images/transparent.gif",
                "end~":"resources/images/transparent.gif",
                "line~":"images/comments/u17_line.png"}}],
          "data":[{
              "column0":{
                "type":"text",
                "text":"1"}},
{
              "column0":{
                "type":"text",
                "text":"2"}},
{
              "column0":{
                "type":"text",
                "text":"3"}}],
          "dataProps":["column0"]},
{
          "id":"b348a72b034e4bcdae377d16fece9514",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":762,
              "y":248},
            "size":{
              "width":80,
              "height":75}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"1bd51b142910419f8aceb41f3d0673e1",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":762,
                  "y":248},
                "size":{
                  "width":80,
                  "height":75}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/home/u58.JPG"}},
{
          "id":"8b7535d4c91747ee96ea135d038b3206",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":532,
              "y":248},
            "size":{
              "width":40,
              "height":40}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7333fac29dca40c38a87a6e2a03fd5a4",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":532,
                  "y":248},
                "size":{
                  "width":40,
                  "height":40}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/comments/u41.png"}},
{
          "id":"ba1a0fda5ff741debb508f899497ae2e",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":582,
              "y":255},
            "size":{
              "width":30,
              "height":25}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e13ec67d91514a1d93d1b224a3120569",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":582,
                  "y":255},
                "size":{
                  "width":30,
                  "height":25}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/comments/u43.png"}},
{
          "id":"01f541ad4f30486691f99a073ab420bf",
          "label":"消息",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":532,
              "y":143},
            "size":{
              "width":25,
              "height":25}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"16cae17224ed4189ae3ada32545ba114",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":532,
                  "y":143},
                "size":{
                  "width":25,
                  "height":25}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 Home",
                      "target":{
                        "targetType":"page",
                        "url":"home.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/pravite/消息_u44.png"}}]}},
  "masters":{
},
  "objectPaths":{
    "89020cef965e416b975765f21840e166":{
      "scriptId":"u0"},
    "e479dcbbe4774a72b49421dc5a2453e2":{
      "scriptId":"u1"},
    "35e91124b43e4824887aef9a5ad2e610":{
      "scriptId":"u2"},
    "a0fd0a1cacfe4ed29e55c17c52336a79":{
      "scriptId":"u3"},
    "66f8ecbe844e421aaf7e23645bf56b93":{
      "scriptId":"u4"},
    "3a615136d8624ff28623f04f9afc4b06":{
      "scriptId":"u5"},
    "a311b622ca534622a2b42dcfb8b56be2":{
      "scriptId":"u6"},
    "a10b13b3023e45cc85e0df89fe46d2a4":{
      "scriptId":"u7"},
    "d4680cafb64e4793b88aeba1cf00d9b1":{
      "scriptId":"u8"},
    "c3b8047ad6094711931d1fc820e6beba":{
      "scriptId":"u9"},
    "896afdf4b89b436d801bf8201f36a1ba":{
      "scriptId":"u10"},
    "52ad66779e874785ae38bc94f5062fa1":{
      "scriptId":"u11"},
    "794d9d0f77204c0fb683178da76482b0":{
      "scriptId":"u12"},
    "0605509805d0416b9313edadb9a7006f":{
      "scriptId":"u13"},
    "794f6fe94cc842b792d3084b84ea14e3":{
      "scriptId":"u14"},
    "6b0261d5851546a19167261e40c6ae15":{
      "scriptId":"u15"},
    "23c63f24d56449e990d4f4444093a79f":{
      "scriptId":"u16"},
    "8a869a36d55d40b2af731f78f07e6523":{
      "scriptId":"u17"},
    "5ccc235c39f646bd96fe01d2834407f2":{
      "scriptId":"u18"},
    "37be3693cf974871a9038a8b6c050fd4":{
      "scriptId":"u19"},
    "52fefa39e0d742fc8d9e984053b12a57":{
      "scriptId":"u20"},
    "bb7bbe9d99e641819de7e9a2e3f53a86":{
      "scriptId":"u21"},
    "cf8fe054777840e1a686a497074edb85":{
      "scriptId":"u22"},
    "fd2ea2b4a8034c7692c3fd5b983d66c4":{
      "scriptId":"u23"},
    "0e0ba34a26694ccb8f7e3374a09eb798":{
      "scriptId":"u24"},
    "7a925e5e1f174b5b98f49ff771727343":{
      "scriptId":"u25"},
    "d7856c43aee74e24bfc6d2d114ab6e31":{
      "scriptId":"u26"},
    "3db35c80716641f2bca2e33d7ce7f5bc":{
      "scriptId":"u27"},
    "215ae78d54a94ba59deb4330df8dc0fc":{
      "scriptId":"u28"},
    "1302eb291dc24863b1e806b65410488f":{
      "scriptId":"u29"},
    "342bd51fdc304cdd889844c20b6cc0c2":{
      "scriptId":"u30"},
    "e01d8fddfe0243a5a9e402a4565052fc":{
      "scriptId":"u31"},
    "e1697d9a0772419da23462b1332c6cd3":{
      "scriptId":"u32"},
    "bf38318186334d3bbe4d81b634336cc4":{
      "scriptId":"u33"},
    "41d47c7766374d91a86fa95d75684f39":{
      "scriptId":"u34"},
    "9edfdc64e36b422ba5061af3ad0bb34b":{
      "scriptId":"u35"},
    "5ee02480243b45abb84e50943dc31eaa":{
      "scriptId":"u36"},
    "780d9e402b864882a56fbef3e97d4000":{
      "scriptId":"u37"},
    "78adbbbd480c4afda57e11ea8f327acb":{
      "scriptId":"u38"},
    "b348a72b034e4bcdae377d16fece9514":{
      "scriptId":"u39"},
    "1bd51b142910419f8aceb41f3d0673e1":{
      "scriptId":"u40"},
    "8b7535d4c91747ee96ea135d038b3206":{
      "scriptId":"u41"},
    "7333fac29dca40c38a87a6e2a03fd5a4":{
      "scriptId":"u42"},
    "ba1a0fda5ff741debb508f899497ae2e":{
      "scriptId":"u43"},
    "e13ec67d91514a1d93d1b224a3120569":{
      "scriptId":"u44"},
    "01f541ad4f30486691f99a073ab420bf":{
      "scriptId":"u45"},
    "16cae17224ed4189ae3ada32545ba114":{
      "scriptId":"u46"}}});