$axure.loadCurrentPage({
  "url":"search.html",
  "generationDate":new Date(1446176365424.66),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable",
"isHiden",
"isHiden2",
"text",
"separater",
"isstarted",
"isshown",
"showpicture"],
  "page":{
    "packageId":"6723a7e8308d44518af4fca1265c509c",
    "type":"Axure:Page",
    "name":"search",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"8c0de7da4feb4fd3af376a0862dce5c7",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "disabled":true,
          "visible":true,
          "style":{
            "size":{
              "width":1348,
              "height":1200}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"9ca32743b9604610912eb4ad00d49f19",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "disabled":true,
              "visible":true,
              "style":{
                "size":{
                  "width":1348,
                  "height":1200}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/home/u0.jpg"}},
{
          "id":"f8e6ddb7399f4f0fb41f751d4958ea1a",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "disabled":true,
          "visible":true,
          "style":{
            "location":{
              "x":490.5,
              "y":0},
            "size":{
              "width":385,
              "height":793},
            "borderWidth":"-1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF000000}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"62c4d61d60f842b8a612b05715ee240d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "disabled":true,
              "visible":true,
              "style":{
                "location":{
                  "x":490.5,
                  "y":0},
                "size":{
                  "width":385,
                  "height":793},
                "borderWidth":"-1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF000000}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/home/u2.png"}},
{
          "id":"65cb09764c894ddaa9a3de5d21e1ef24",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":522,
              "y":173},
            "size":{
              "width":320,
              "height":507}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"322c1184860d45f7b9eb5b63c3bb76b6",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":522,
                  "y":173},
                "size":{
                  "width":320,
                  "height":507}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/pravite/u4.png"}},
{
          "id":"972d5ad3b55f48f5ac1dc6e09e52f358",
          "label":"状态栏",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFFF9999},
            "location":{
              "x":522,
              "y":113},
            "size":{
              "width":320,
              "height":20},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFF9999}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"30057425847640269f6a3d0bfc08c9cf",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFF9999},
                "location":{
                  "x":522,
                  "y":113},
                "size":{
                  "width":320,
                  "height":20},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFF9999}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/search/状态栏_u6.png"}},
{
          "id":"c4cd1142bc2743fca99f14902bb2ec47",
          "label":"框架",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Charlemagne Std Bold', 'Charlemagne Std'",
            "fontSize":"14px",
            "fontWeight":"700",
            "lineSpacing":"20px",
            "fill":{
              "fillType":"solid",
              "color":0xFFFF9999},
            "location":{
              "x":522,
              "y":133},
            "size":{
              "width":320,
              "height":40},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFF9999}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c0797d7b2d5d424787e4c06bec5a0d45",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Charlemagne Std Bold', 'Charlemagne Std'",
                "fontSize":"14px",
                "fontWeight":"700",
                "lineSpacing":"20px",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFF9999},
                "location":{
                  "x":522,
                  "y":133},
                "size":{
                  "width":320,
                  "height":40},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFF9999}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/search/框架_u8.png"}},
{
          "id":"742dddbae2214f069a919ac578c378b8",
          "label":"搜索输入",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF999999,
              "opacity":1},
            "location":{
              "x":577,
              "y":138},
            "size":{
              "width":210,
              "height":25}},
          "adaptiveStyles":{
},
          "placeholderText":"搜索地点、标签"},
{
          "id":"e5747ee617d842cfbaf171f41e1558c4",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":522,
              "y":209},
            "size":{
              "width":320,
              "height":10},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF797979}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/search/u11_line.png"}},
{
          "id":"ce6399ad5e344426823d0bf9529a6b41",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":522,
              "y":309},
            "size":{
              "width":320,
              "height":10},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF797979}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/search/u11_line.png"}},
{
          "id":"ec0790511ce7432baa4f3936d0454c79",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":552,
              "y":186},
            "size":{
              "width":300,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"50fff57e99e44aa0a76309d6263e4aec",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":552,
                  "y":186},
                "size":{
                  "width":300,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"0aec225214f64869bd4311301079c008",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":552,
              "y":237},
            "size":{
              "width":300,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"54ade951908b47589b955ff6363550bf",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":552,
                  "y":237},
                "size":{
                  "width":300,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"31ff34f8c69d4777925bb102634765b5",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":522,
              "y":263},
            "size":{
              "width":320,
              "height":10},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF797979}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/search/u11_line.png"}},
{
          "id":"dd344dfd957649528140b108b124de19",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":552,
              "y":283},
            "size":{
              "width":300,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"87b73b851c884ca5bf7ac84b29f8cd1a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":552,
                  "y":283},
                "size":{
                  "width":300,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"7c79eb00a140497997042cd8fc029f14",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":522,
              "y":355},
            "size":{
              "width":320,
              "height":10},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF797979}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/search/u11_line.png"}},
{
          "id":"702ae9cfc56b4c3897966507a86af3c4",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":552,
              "y":329},
            "size":{
              "width":300,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8327cc10408444ad9af04cbc11fb540e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":552,
                  "y":329},
                "size":{
                  "width":300,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"77ffb9d9272b4917a3956fca9eb21d8f",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":522,
              "y":393},
            "size":{
              "width":320,
              "height":10},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF797979}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/search/u11_line.png"}},
{
          "id":"c5ac9383913e4102ace4aee73d098038",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":522,
              "y":433},
            "size":{
              "width":320,
              "height":10},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF797979}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/search/u11_line.png"}},
{
          "id":"b5ad4ddfe30f429c9d042f864410c3f7",
          "label":"消息",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":532,
              "y":143},
            "size":{
              "width":25,
              "height":25}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f1bf7e09ac9145288d3ef5608f99d2af",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":532,
                  "y":143},
                "size":{
                  "width":25,
                  "height":25}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 Home",
                      "target":{
                        "targetType":"page",
                        "url":"home.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/pravite/消息_u44.png"}}]}},
  "masters":{
},
  "objectPaths":{
    "8c0de7da4feb4fd3af376a0862dce5c7":{
      "scriptId":"u0"},
    "9ca32743b9604610912eb4ad00d49f19":{
      "scriptId":"u1"},
    "f8e6ddb7399f4f0fb41f751d4958ea1a":{
      "scriptId":"u2"},
    "62c4d61d60f842b8a612b05715ee240d":{
      "scriptId":"u3"},
    "65cb09764c894ddaa9a3de5d21e1ef24":{
      "scriptId":"u4"},
    "322c1184860d45f7b9eb5b63c3bb76b6":{
      "scriptId":"u5"},
    "972d5ad3b55f48f5ac1dc6e09e52f358":{
      "scriptId":"u6"},
    "30057425847640269f6a3d0bfc08c9cf":{
      "scriptId":"u7"},
    "c4cd1142bc2743fca99f14902bb2ec47":{
      "scriptId":"u8"},
    "c0797d7b2d5d424787e4c06bec5a0d45":{
      "scriptId":"u9"},
    "742dddbae2214f069a919ac578c378b8":{
      "scriptId":"u10"},
    "e5747ee617d842cfbaf171f41e1558c4":{
      "scriptId":"u11"},
    "ce6399ad5e344426823d0bf9529a6b41":{
      "scriptId":"u12"},
    "ec0790511ce7432baa4f3936d0454c79":{
      "scriptId":"u13"},
    "50fff57e99e44aa0a76309d6263e4aec":{
      "scriptId":"u14"},
    "0aec225214f64869bd4311301079c008":{
      "scriptId":"u15"},
    "54ade951908b47589b955ff6363550bf":{
      "scriptId":"u16"},
    "31ff34f8c69d4777925bb102634765b5":{
      "scriptId":"u17"},
    "dd344dfd957649528140b108b124de19":{
      "scriptId":"u18"},
    "87b73b851c884ca5bf7ac84b29f8cd1a":{
      "scriptId":"u19"},
    "7c79eb00a140497997042cd8fc029f14":{
      "scriptId":"u20"},
    "702ae9cfc56b4c3897966507a86af3c4":{
      "scriptId":"u21"},
    "8327cc10408444ad9af04cbc11fb540e":{
      "scriptId":"u22"},
    "77ffb9d9272b4917a3956fca9eb21d8f":{
      "scriptId":"u23"},
    "c5ac9383913e4102ace4aee73d098038":{
      "scriptId":"u24"},
    "b5ad4ddfe30f429c9d042f864410c3f7":{
      "scriptId":"u25"},
    "f1bf7e09ac9145288d3ef5608f99d2af":{
      "scriptId":"u26"}}});