$axure.loadCurrentPage({
  "url":"settings.html",
  "generationDate":new Date(1446176366126.38),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable",
"isHiden",
"isHiden2",
"text",
"separater",
"isstarted",
"isshown",
"showpicture"],
  "page":{
    "packageId":"41a8ae82758c4e5f9b595cedbec3339f",
    "type":"Axure:Page",
    "name":"settings",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"5a2027ee1a304432ba10fc8f1a82714b",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "disabled":true,
          "visible":true,
          "style":{
            "size":{
              "width":1348,
              "height":1200}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"12921087fe7844718c10780220c3d3da",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "disabled":true,
              "visible":true,
              "style":{
                "size":{
                  "width":1348,
                  "height":1200}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/home/u0.jpg"}},
{
          "id":"003e1cb36ca64928ad8cc981c5995731",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "disabled":true,
          "visible":true,
          "style":{
            "location":{
              "x":490.5,
              "y":0},
            "size":{
              "width":385,
              "height":793},
            "borderWidth":"-1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF000000}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"462897b047f94ab1b014e578fbbace70",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "disabled":true,
              "visible":true,
              "style":{
                "location":{
                  "x":490.5,
                  "y":0},
                "size":{
                  "width":385,
                  "height":793},
                "borderWidth":"-1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF000000}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/home/u2.png"}},
{
          "id":"0e6763f90e7049378c116324e117fd72",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":522,
              "y":173},
            "size":{
              "width":320,
              "height":507}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"0887c2fd4d8942e59eb60c2c574e34ab",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":522,
                  "y":173},
                "size":{
                  "width":320,
                  "height":507}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/pravite/u4.png"}},
{
          "id":"85023bc65d07499fb644302779c36183",
          "label":"状态栏",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFFF6666},
            "location":{
              "x":522,
              "y":113},
            "size":{
              "width":320,
              "height":20},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFF6666}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"535e15a49b724dd187956264aa1734fe",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFF6666},
                "location":{
                  "x":522,
                  "y":113},
                "size":{
                  "width":320,
                  "height":20},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFF6666}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/home/状态栏_u31.png"}},
{
          "id":"8b3418db86fd4fb5a78d1682d7b778b0",
          "label":"框架",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Charlemagne Std Bold', 'Charlemagne Std'",
            "fontSize":"14px",
            "fontWeight":"700",
            "lineSpacing":"20px",
            "fill":{
              "fillType":"solid",
              "color":0xFFFF6666},
            "location":{
              "x":522,
              "y":133},
            "size":{
              "width":320,
              "height":40},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFF6666}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4a7b6b4681344553bb47759cf4b1048c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Charlemagne Std Bold', 'Charlemagne Std'",
                "fontSize":"14px",
                "fontWeight":"700",
                "lineSpacing":"20px",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFF6666},
                "location":{
                  "x":522,
                  "y":133},
                "size":{
                  "width":320,
                  "height":40},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFF6666}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/home/框架_u33.png"}},
{
          "id":"6655ccdb650e4500b269e637e2d126c9",
          "label":"消息",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":532,
              "y":143},
            "size":{
              "width":25,
              "height":25}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8f26540ae18544cf85ba0a7c21e49c5a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":532,
                  "y":143},
                "size":{
                  "width":25,
                  "height":25}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 Home",
                      "target":{
                        "targetType":"page",
                        "url":"home.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/pravite/消息_u44.png"}},
{
          "id":"d3faf96ea8e143ff99c54e2f55516f9b",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "fontSize":"20px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "location":{
              "x":662,
              "y":139},
            "size":{
              "width":41,
              "height":27}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"96968e7d62df4482879a60ca372967e0",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "fontSize":"20px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "location":{
                  "x":662,
                  "y":139},
                "size":{
                  "width":41,
                  "height":27}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"a5c75fd7e85d4f86b158aaab7eac6e15",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":542,
              "y":199},
            "size":{
              "width":300,
              "height":80}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a942dfd007ab456291d85728917decb5",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":542,
                  "y":199},
                "size":{
                  "width":300,
                  "height":80}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}}]}},
  "masters":{
},
  "objectPaths":{
    "5a2027ee1a304432ba10fc8f1a82714b":{
      "scriptId":"u0"},
    "12921087fe7844718c10780220c3d3da":{
      "scriptId":"u1"},
    "003e1cb36ca64928ad8cc981c5995731":{
      "scriptId":"u2"},
    "462897b047f94ab1b014e578fbbace70":{
      "scriptId":"u3"},
    "0e6763f90e7049378c116324e117fd72":{
      "scriptId":"u4"},
    "0887c2fd4d8942e59eb60c2c574e34ab":{
      "scriptId":"u5"},
    "85023bc65d07499fb644302779c36183":{
      "scriptId":"u6"},
    "535e15a49b724dd187956264aa1734fe":{
      "scriptId":"u7"},
    "8b3418db86fd4fb5a78d1682d7b778b0":{
      "scriptId":"u8"},
    "4a7b6b4681344553bb47759cf4b1048c":{
      "scriptId":"u9"},
    "6655ccdb650e4500b269e637e2d126c9":{
      "scriptId":"u10"},
    "8f26540ae18544cf85ba0a7c21e49c5a":{
      "scriptId":"u11"},
    "d3faf96ea8e143ff99c54e2f55516f9b":{
      "scriptId":"u12"},
    "96968e7d62df4482879a60ca372967e0":{
      "scriptId":"u13"},
    "a5c75fd7e85d4f86b158aaab7eac6e15":{
      "scriptId":"u14"},
    "a942dfd007ab456291d85728917decb5":{
      "scriptId":"u15"}}});