$axure.loadCurrentPage({
  "url":"picture.html",
  "generationDate":new Date(1446176366035.32),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable",
"isHiden",
"isHiden2",
"text",
"separater",
"isstarted",
"isshown",
"showpicture"],
  "page":{
    "packageId":"fc6fd0fe40974dd7aa1f9e271a88cb17",
    "type":"Axure:Page",
    "name":"picture",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"a3b4636055d54dadaadd990df4c704af",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "disabled":true,
          "visible":true,
          "style":{
            "size":{
              "width":1348,
              "height":1200}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"164addf9611c4f4db1751dafc7c59f45",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "disabled":true,
              "visible":true,
              "style":{
                "size":{
                  "width":1348,
                  "height":1200}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/home/u0.jpg"}},
{
          "id":"8fff92455553412bac558a3571fcb192",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "disabled":true,
          "visible":true,
          "style":{
            "location":{
              "x":490.5,
              "y":0},
            "size":{
              "width":385,
              "height":793},
            "borderWidth":"-1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF000000}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7b154f8a0c3741ef8d2ed5e01ea5d56a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "disabled":true,
              "visible":true,
              "style":{
                "location":{
                  "x":490.5,
                  "y":0},
                "size":{
                  "width":385,
                  "height":793},
                "borderWidth":"-1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF000000}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/home/u2.png"}},
{
          "id":"7a50d671ca94453daa1023669cbd05c0",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":522,
              "y":173},
            "size":{
              "width":320,
              "height":507}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4eb9977300f44136917d1fa6fae7c032",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":522,
                  "y":173},
                "size":{
                  "width":320,
                  "height":507}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/pravite/u4.png"}},
{
          "id":"159a595f2ee548dbb77cbd70a220e928",
          "label":"状态栏",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFFF6666},
            "location":{
              "x":522,
              "y":113},
            "size":{
              "width":320,
              "height":20},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFF6666}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d39512f182b7419cb70e3f14c38394a9",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFF6666},
                "location":{
                  "x":522,
                  "y":113},
                "size":{
                  "width":320,
                  "height":20},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFF6666}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/home/状态栏_u31.png"}},
{
          "id":"26eb18bb8b764f07bd22ec7e4421acd8",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Charlemagne Std Bold', 'Charlemagne Std'",
            "fontSize":"14px",
            "fontWeight":"700",
            "lineSpacing":"20px",
            "fill":{
              "fillType":"solid",
              "color":0xFFFF6666},
            "location":{
              "x":522,
              "y":133},
            "size":{
              "width":320,
              "height":40},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFF6666}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a4a86139763b45698491113eeccaf5d2",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Charlemagne Std Bold', 'Charlemagne Std'",
                "fontSize":"14px",
                "fontWeight":"700",
                "lineSpacing":"20px",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFF6666},
                "location":{
                  "x":522,
                  "y":133},
                "size":{
                  "width":320,
                  "height":40},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFF6666}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/home/框架_u33.png"}},
{
          "id":"9d4ec3db79264495a9b9860c91ad3401",
          "label":"消息",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":532,
              "y":138},
            "size":{
              "width":25,
              "height":25}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e492704336af4ef99c583766a8ff1e8e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":532,
                  "y":138},
                "size":{
                  "width":25,
                  "height":25}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 Home",
                      "target":{
                        "targetType":"page",
                        "url":"home.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/pravite/消息_u44.png"}},
{
          "id":"e15d471d72a1488f9fd90894fc708953",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":522,
              "y":351},
            "size":{
              "width":320,
              "height":10},
            "borderWidth":"5",
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFF6666}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/home/u146_line.png"}},
{
          "id":"5b31fff1398e4358bbc7e61e68a09332",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":522,
              "y":671},
            "size":{
              "width":320,
              "height":10},
            "borderWidth":"5",
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFF6666}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/home/u146_line.png"}},
{
          "id":"292fa628df884573a676aceb6239dac6",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":522,
              "y":168},
            "size":{
              "width":320,
              "height":183}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"05516262cc75428ba8c686e50493b008",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":522,
                  "y":168},
                "size":{
                  "width":320,
                  "height":183}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/picture/u14.png"}},
{
          "id":"1fc7aa46bcf149bc96f03ebb161ecbf0",
          "label":"故事版",
          "type":"dynamicPanel",
          "styleType":"dynamicPanel",
          "visible":true,
          "style":{
            "location":{
              "x":522,
              "y":361},
            "size":{
              "width":320,
              "height":310}},
          "adaptiveStyles":{
},
          "interactionMap":{
            "onDrag":{
              "description":"OnDrag",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"moveWidget",
                      "description":"移动 (形状) y 轴拖动,<br>(图片) y 轴拖动,<br>(图片) y 轴拖动,<br>(图片) y 轴拖动,<br>(形状) y 轴拖动,<br>(垂直线) y 轴拖动,<br>(形状) y 轴拖动,<br>(图片) y 轴拖动,<br>(形状) y 轴拖动",
                      "objectsToMoves":[{
                          "objectPath":["1454158c068a4b0a860c614bb34c4ef8"],
                          "moveInfo":{
                            "moveType":"dragY",
                            "xValue":{
                              "exprType":"stringLiteral",
                              "value":"0",
                              "stos":[]},
                            "yValue":{
                              "exprType":"stringLiteral",
                              "value":"0",
                              "stos":[]},
                            "options":{
}}},
{
                          "objectPath":["78044aa9b84f443bad3cac76020d6154"],
                          "moveInfo":{
                            "moveType":"dragY",
                            "xValue":{
                              "exprType":"stringLiteral",
                              "value":"0",
                              "stos":[]},
                            "yValue":{
                              "exprType":"stringLiteral",
                              "value":"0",
                              "stos":[]},
                            "options":{
}}},
{
                          "objectPath":["73c05c7cfa2a4222b38576fdf65b3436"],
                          "moveInfo":{
                            "moveType":"dragY",
                            "xValue":{
                              "exprType":"stringLiteral",
                              "value":"0",
                              "stos":[]},
                            "yValue":{
                              "exprType":"stringLiteral",
                              "value":"0",
                              "stos":[]},
                            "options":{
}}},
{
                          "objectPath":["cc481c25160240b49f789f4a6e2a0f02"],
                          "moveInfo":{
                            "moveType":"dragY",
                            "xValue":{
                              "exprType":"stringLiteral",
                              "value":"0",
                              "stos":[]},
                            "yValue":{
                              "exprType":"stringLiteral",
                              "value":"0",
                              "stos":[]},
                            "options":{
}}},
{
                          "objectPath":["443aae754b7a4c43a1151f5437ffb586"],
                          "moveInfo":{
                            "moveType":"dragY",
                            "xValue":{
                              "exprType":"stringLiteral",
                              "value":"0",
                              "stos":[]},
                            "yValue":{
                              "exprType":"stringLiteral",
                              "value":"0",
                              "stos":[]},
                            "options":{
}}},
{
                          "objectPath":["f1c67cd6411d4f9b9a96d9b25c16740a"],
                          "moveInfo":{
                            "moveType":"dragY",
                            "xValue":{
                              "exprType":"stringLiteral",
                              "value":"0",
                              "stos":[]},
                            "yValue":{
                              "exprType":"stringLiteral",
                              "value":"0",
                              "stos":[]},
                            "options":{
}}},
{
                          "objectPath":["c672df09d6bb4a5e917ebf9b058e3455"],
                          "moveInfo":{
                            "moveType":"dragY",
                            "xValue":{
                              "exprType":"stringLiteral",
                              "value":"0",
                              "stos":[]},
                            "yValue":{
                              "exprType":"stringLiteral",
                              "value":"0",
                              "stos":[]},
                            "options":{
}}},
{
                          "objectPath":["17e3529fb1fd437b87daba197844cc41"],
                          "moveInfo":{
                            "moveType":"dragY",
                            "xValue":{
                              "exprType":"stringLiteral",
                              "value":"0",
                              "stos":[]},
                            "yValue":{
                              "exprType":"stringLiteral",
                              "value":"0",
                              "stos":[]},
                            "options":{
}}},
{
                          "objectPath":["21604b0716064614b16ca66d8a5a87e5"],
                          "moveInfo":{
                            "moveType":"dragY",
                            "xValue":{
                              "exprType":"stringLiteral",
                              "value":"0",
                              "stos":[]},
                            "yValue":{
                              "exprType":"stringLiteral",
                              "value":"0",
                              "stos":[]},
                            "options":{
}}}]}]}]}},
          "scrollbars":"none",
          "fitToContent":false,
          "propagate":false,
          "diagrams":[{
              "id":"b330c84b985a40d68c0127b4eaf1a967",
              "label":"State1",
              "type":"Axure:PanelDiagram",
              "objects":[{
                  "id":"17e3529fb1fd437b87daba197844cc41",
                  "label":"",
                  "parentDynamicPanel":"1fc7aa46bcf149bc96f03ebb161ecbf0",
                  "type":"imageBox",
                  "styleType":"imageBox",
                  "visible":true,
                  "style":{
                    "size":{
                      "width":140,
                      "height":140}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"dbef9c83045147a7b1af009c6dc81dc0",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"1fc7aa46bcf149bc96f03ebb161ecbf0",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "size":{
                          "width":140,
                          "height":140}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/picture/u17.JPG"}},
{
                  "id":"c672df09d6bb4a5e917ebf9b058e3455",
                  "label":"",
                  "parentDynamicPanel":"1fc7aa46bcf149bc96f03ebb161ecbf0",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":160,
                      "y":14},
                    "size":{
                      "width":150,
                      "height":112}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"a337346396b04cceaa19e9190176a10f",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"1fc7aa46bcf149bc96f03ebb161ecbf0",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":160,
                          "y":14},
                        "size":{
                          "width":150,
                          "height":112}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"f1c67cd6411d4f9b9a96d9b25c16740a",
                  "label":"",
                  "parentDynamicPanel":"1fc7aa46bcf149bc96f03ebb161ecbf0",
                  "type":"verticalLine",
                  "styleType":"verticalLine",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":150,
                      "y":0},
                    "size":{
                      "width":10,
                      "height":640},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFFCCCCCC}},
                  "adaptiveStyles":{
},
                  "images":{
                    "start~":"resources/images/transparent.gif",
                    "end~":"resources/images/transparent.gif",
                    "line~":"images/picture/u21_line.png"}},
{
                  "id":"443aae754b7a4c43a1151f5437ffb586",
                  "label":"",
                  "parentDynamicPanel":"1fc7aa46bcf149bc96f03ebb161ecbf0",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":160,
                      "y":174},
                    "size":{
                      "width":150,
                      "height":112}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"1d56f58cd9cf4c10a89621de632e58f7",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"1fc7aa46bcf149bc96f03ebb161ecbf0",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":160,
                          "y":174},
                        "size":{
                          "width":150,
                          "height":112}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"21604b0716064614b16ca66d8a5a87e5",
                  "label":"",
                  "parentDynamicPanel":"1fc7aa46bcf149bc96f03ebb161ecbf0",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":160,
                      "y":334},
                    "size":{
                      "width":150,
                      "height":112}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"1ef3d6c796694278a8d3fc799cf65a16",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"1fc7aa46bcf149bc96f03ebb161ecbf0",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":160,
                          "y":334},
                        "size":{
                          "width":150,
                          "height":112}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"cc481c25160240b49f789f4a6e2a0f02",
                  "label":"",
                  "parentDynamicPanel":"1fc7aa46bcf149bc96f03ebb161ecbf0",
                  "type":"imageBox",
                  "styleType":"imageBox",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":0,
                      "y":160},
                    "size":{
                      "width":140,
                      "height":140}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"80f17ea26a3044c79854d40494cd2f7e",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"1fc7aa46bcf149bc96f03ebb161ecbf0",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":0,
                          "y":160},
                        "size":{
                          "width":140,
                          "height":140}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/picture/u26.JPG"}},
{
                  "id":"73c05c7cfa2a4222b38576fdf65b3436",
                  "label":"",
                  "parentDynamicPanel":"1fc7aa46bcf149bc96f03ebb161ecbf0",
                  "type":"imageBox",
                  "styleType":"imageBox",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":0,
                      "y":320},
                    "size":{
                      "width":140,
                      "height":140}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"933dcd35fac242dfaba0621e1a5bacf2",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"1fc7aa46bcf149bc96f03ebb161ecbf0",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":0,
                          "y":320},
                        "size":{
                          "width":140,
                          "height":140}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/picture/u28.JPG"}},
{
                  "id":"78044aa9b84f443bad3cac76020d6154",
                  "label":"",
                  "parentDynamicPanel":"1fc7aa46bcf149bc96f03ebb161ecbf0",
                  "type":"imageBox",
                  "styleType":"imageBox",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":0,
                      "y":480},
                    "size":{
                      "width":140,
                      "height":140}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"5ae6985ab63e45299d88124d08030965",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"1fc7aa46bcf149bc96f03ebb161ecbf0",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":0,
                          "y":480},
                        "size":{
                          "width":140,
                          "height":140}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/picture/u30.JPG"}},
{
                  "id":"1454158c068a4b0a860c614bb34c4ef8",
                  "label":"",
                  "parentDynamicPanel":"1fc7aa46bcf149bc96f03ebb161ecbf0",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":160,
                      "y":494},
                    "size":{
                      "width":150,
                      "height":112}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"40467d7595e44ba5a6089cece0dd8ca4",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"1fc7aa46bcf149bc96f03ebb161ecbf0",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":160,
                          "y":494},
                        "size":{
                          "width":150,
                          "height":112}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}}]}]},
{
          "id":"ae8c046369de407a828bdad036035b04",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "fontSize":"20px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "location":{
              "x":632,
              "y":138},
            "size":{
              "width":101,
              "height":27}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c5f327034019407ca4aa83629a0456bb",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "fontSize":"20px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "location":{
                  "x":632,
                  "y":138},
                "size":{
                  "width":101,
                  "height":27}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"d78094e3d54d4e5a87d849c5a08c1ff8",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":802,
              "y":173},
            "size":{
              "width":30,
              "height":32}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f3124c3d8b424fd2916562c6764048a5",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":802,
                  "y":173},
                "size":{
                  "width":30,
                  "height":32}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/picture/u36.png"}},
{
          "id":"5a3d8d03657247dd80b5f6a1de0270e7",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":806.5,
              "y":205},
            "size":{
              "width":21,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"062ed91865d34d88a691772035256e6d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":806.5,
                  "y":205},
                "size":{
                  "width":21,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/picture/u38.png"}},
{
          "id":"f25ccb1d34e04f78a24810f441da374a",
          "label":"消息",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":802,
              "y":133},
            "size":{
              "width":25,
              "height":30}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"64ee1a72995947439d36bc71b5a3e8f9",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":802,
                  "y":133},
                "size":{
                  "width":25,
                  "height":30}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/achievement/消息_u38.png"}}]}},
  "masters":{
},
  "objectPaths":{
    "a3b4636055d54dadaadd990df4c704af":{
      "scriptId":"u0"},
    "164addf9611c4f4db1751dafc7c59f45":{
      "scriptId":"u1"},
    "8fff92455553412bac558a3571fcb192":{
      "scriptId":"u2"},
    "7b154f8a0c3741ef8d2ed5e01ea5d56a":{
      "scriptId":"u3"},
    "7a50d671ca94453daa1023669cbd05c0":{
      "scriptId":"u4"},
    "4eb9977300f44136917d1fa6fae7c032":{
      "scriptId":"u5"},
    "159a595f2ee548dbb77cbd70a220e928":{
      "scriptId":"u6"},
    "d39512f182b7419cb70e3f14c38394a9":{
      "scriptId":"u7"},
    "26eb18bb8b764f07bd22ec7e4421acd8":{
      "scriptId":"u8"},
    "a4a86139763b45698491113eeccaf5d2":{
      "scriptId":"u9"},
    "9d4ec3db79264495a9b9860c91ad3401":{
      "scriptId":"u10"},
    "e492704336af4ef99c583766a8ff1e8e":{
      "scriptId":"u11"},
    "e15d471d72a1488f9fd90894fc708953":{
      "scriptId":"u12"},
    "5b31fff1398e4358bbc7e61e68a09332":{
      "scriptId":"u13"},
    "292fa628df884573a676aceb6239dac6":{
      "scriptId":"u14"},
    "05516262cc75428ba8c686e50493b008":{
      "scriptId":"u15"},
    "1fc7aa46bcf149bc96f03ebb161ecbf0":{
      "scriptId":"u16"},
    "17e3529fb1fd437b87daba197844cc41":{
      "scriptId":"u17"},
    "dbef9c83045147a7b1af009c6dc81dc0":{
      "scriptId":"u18"},
    "c672df09d6bb4a5e917ebf9b058e3455":{
      "scriptId":"u19"},
    "a337346396b04cceaa19e9190176a10f":{
      "scriptId":"u20"},
    "f1c67cd6411d4f9b9a96d9b25c16740a":{
      "scriptId":"u21"},
    "443aae754b7a4c43a1151f5437ffb586":{
      "scriptId":"u22"},
    "1d56f58cd9cf4c10a89621de632e58f7":{
      "scriptId":"u23"},
    "21604b0716064614b16ca66d8a5a87e5":{
      "scriptId":"u24"},
    "1ef3d6c796694278a8d3fc799cf65a16":{
      "scriptId":"u25"},
    "cc481c25160240b49f789f4a6e2a0f02":{
      "scriptId":"u26"},
    "80f17ea26a3044c79854d40494cd2f7e":{
      "scriptId":"u27"},
    "73c05c7cfa2a4222b38576fdf65b3436":{
      "scriptId":"u28"},
    "933dcd35fac242dfaba0621e1a5bacf2":{
      "scriptId":"u29"},
    "78044aa9b84f443bad3cac76020d6154":{
      "scriptId":"u30"},
    "5ae6985ab63e45299d88124d08030965":{
      "scriptId":"u31"},
    "1454158c068a4b0a860c614bb34c4ef8":{
      "scriptId":"u32"},
    "40467d7595e44ba5a6089cece0dd8ca4":{
      "scriptId":"u33"},
    "ae8c046369de407a828bdad036035b04":{
      "scriptId":"u34"},
    "c5f327034019407ca4aa83629a0456bb":{
      "scriptId":"u35"},
    "d78094e3d54d4e5a87d849c5a08c1ff8":{
      "scriptId":"u36"},
    "f3124c3d8b424fd2916562c6764048a5":{
      "scriptId":"u37"},
    "5a3d8d03657247dd80b5f6a1de0270e7":{
      "scriptId":"u38"},
    "062ed91865d34d88a691772035256e6d":{
      "scriptId":"u39"},
    "f25ccb1d34e04f78a24810f441da374a":{
      "scriptId":"u40"},
    "64ee1a72995947439d36bc71b5a3e8f9":{
      "scriptId":"u41"}}});