$axure.loadCurrentPage({
  "url":"pravite.html",
  "generationDate":new Date(1446176365151.13),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable",
"isHiden",
"isHiden2",
"text",
"separater",
"isstarted",
"isshown",
"showpicture"],
  "page":{
    "packageId":"5ac933a968d14397b93124e73e47b69f",
    "type":"Axure:Page",
    "name":"pravite",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"86894ea838eb4b97b65a12f9a5611989",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "disabled":true,
          "visible":true,
          "style":{
            "size":{
              "width":1348,
              "height":1200}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"218ac75ffa0144c7a8ab950760360a9e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "disabled":true,
              "visible":true,
              "style":{
                "size":{
                  "width":1348,
                  "height":1200}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/home/u0.jpg"}},
{
          "id":"4186b90d44cb43e0a621520bf6e8c7de",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "disabled":true,
          "visible":true,
          "style":{
            "location":{
              "x":490.5,
              "y":0},
            "size":{
              "width":385,
              "height":793},
            "borderWidth":"-1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF000000}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"34ffd273a28b4b7dbd47fca3d9480821",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "disabled":true,
              "visible":true,
              "style":{
                "location":{
                  "x":490.5,
                  "y":0},
                "size":{
                  "width":385,
                  "height":793},
                "borderWidth":"-1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF000000}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/home/u2.png"}},
{
          "id":"d70b9aaa4ad64b7b92649b828031464e",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":522,
              "y":173},
            "size":{
              "width":320,
              "height":507}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"de714c94323a44c7a875bad4fbd33ef6",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":522,
                  "y":173},
                "size":{
                  "width":320,
                  "height":507}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/pravite/u4.png"}},
{
          "id":"272a7f37f7dd42c3b342d2b3f9a6a9a8",
          "label":"hiden2",
          "type":"dynamicPanel",
          "styleType":"dynamicPanel",
          "visible":true,
          "selected":true,
          "style":{
            "location":{
              "x":522,
              "y":112},
            "size":{
              "width":200,
              "height":568}},
          "adaptiveStyles":{
},
          "interactionMap":{
            "onDrag":{
              "description":"OnDrag",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"moveWidget",
                      "description":"移动 (图片) y 轴拖动,<br>(形状) y 轴拖动,<br>(图片) y 轴拖动,<br>(图片) y 轴拖动,<br>(形状) y 轴拖动,<br>(图片) y 轴拖动,<br>(形状) y 轴拖动,<br>(图片) y 轴拖动,<br>(形状) y 轴拖动",
                      "objectsToMoves":[{
                          "objectPath":["feb51bfcd22547c098b7a77784136d6d"],
                          "moveInfo":{
                            "moveType":"dragY",
                            "xValue":{
                              "exprType":"stringLiteral",
                              "value":"0",
                              "stos":[]},
                            "yValue":{
                              "exprType":"stringLiteral",
                              "value":"0",
                              "stos":[]},
                            "options":{
}}},
{
                          "objectPath":["731ab865dfe347e29b5f91b9cede93e9"],
                          "moveInfo":{
                            "moveType":"dragY",
                            "xValue":{
                              "exprType":"stringLiteral",
                              "value":"0",
                              "stos":[]},
                            "yValue":{
                              "exprType":"stringLiteral",
                              "value":"0",
                              "stos":[]},
                            "options":{
}}},
{
                          "objectPath":["54b22f8b6aef4561a190bcd9fd381381"],
                          "moveInfo":{
                            "moveType":"dragY",
                            "xValue":{
                              "exprType":"stringLiteral",
                              "value":"0",
                              "stos":[]},
                            "yValue":{
                              "exprType":"stringLiteral",
                              "value":"0",
                              "stos":[]},
                            "options":{
}}},
{
                          "objectPath":["5631a2e1db28466e84115e56ec99dad9"],
                          "moveInfo":{
                            "moveType":"dragY",
                            "xValue":{
                              "exprType":"stringLiteral",
                              "value":"0",
                              "stos":[]},
                            "yValue":{
                              "exprType":"stringLiteral",
                              "value":"0",
                              "stos":[]},
                            "options":{
}}},
{
                          "objectPath":["b0d68feca03a4614923db042f28a77e5"],
                          "moveInfo":{
                            "moveType":"dragY",
                            "xValue":{
                              "exprType":"stringLiteral",
                              "value":"0",
                              "stos":[]},
                            "yValue":{
                              "exprType":"stringLiteral",
                              "value":"0",
                              "stos":[]},
                            "options":{
}}},
{
                          "objectPath":["39858814004945368b0da783b5941f1d"],
                          "moveInfo":{
                            "moveType":"dragY",
                            "xValue":{
                              "exprType":"stringLiteral",
                              "value":"0",
                              "stos":[]},
                            "yValue":{
                              "exprType":"stringLiteral",
                              "value":"0",
                              "stos":[]},
                            "options":{
}}},
{
                          "objectPath":["6f2b0cfa15a544d8a680dce07426b4dd"],
                          "moveInfo":{
                            "moveType":"dragY",
                            "xValue":{
                              "exprType":"stringLiteral",
                              "value":"0",
                              "stos":[]},
                            "yValue":{
                              "exprType":"stringLiteral",
                              "value":"0",
                              "stos":[]},
                            "options":{
}}},
{
                          "objectPath":["027d2d8feaab46459b4ac182025615b8"],
                          "moveInfo":{
                            "moveType":"dragY",
                            "xValue":{
                              "exprType":"stringLiteral",
                              "value":"0",
                              "stos":[]},
                            "yValue":{
                              "exprType":"stringLiteral",
                              "value":"0",
                              "stos":[]},
                            "options":{
}}},
{
                          "objectPath":["155eb60265dd4e71bb0fd01eefde5ec8"],
                          "moveInfo":{
                            "moveType":"dragY",
                            "xValue":{
                              "exprType":"stringLiteral",
                              "value":"0",
                              "stos":[]},
                            "yValue":{
                              "exprType":"stringLiteral",
                              "value":"0",
                              "stos":[]},
                            "options":{
}}}]}]}]},
            "onSwipeRight":{
              "description":"OnSwipeRight",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"setFunction",
                      "description":"设置 值于 isHiden2 = &quot;true&quot;",
                      "expr":{
                        "exprType":"block",
                        "subExprs":[{
                            "exprType":"fcall",
                            "functionName":"SetGlobalVariableValue",
                            "arguments":[{
                                "exprType":"globalVariableLiteral",
                                "variableName":"isHiden2"},
{
                                "exprType":"stringLiteral",
                                "value":"true",
                                "stos":[]}]}]}},
{
                      "action":"moveWidget",
                      "description":"移动 private 到 (0,0) 线性 500ms",
                      "objectsToMoves":[{
                          "objectPath":["c7cda6dd7f3a4831865e587c715c9b1a"],
                          "moveInfo":{
                            "moveType":"location",
                            "xValue":{
                              "exprType":"stringLiteral",
                              "value":"0",
                              "stos":[]},
                            "yValue":{
                              "exprType":"stringLiteral",
                              "value":"0",
                              "stos":[]},
                            "options":{
                              "easing":"linear",
                              "duration":500}}}]}]}]}},
          "scrollbars":"none",
          "fitToContent":false,
          "propagate":false,
          "diagrams":[{
              "id":"9b928def5c604704842b12c4aa41cd0b",
              "label":"State1",
              "type":"Axure:PanelDiagram",
              "objects":[{
                  "id":"5cf7e0063fcd4b2c95540802ef757a05",
                  "label":"",
                  "parentDynamicPanel":"272a7f37f7dd42c3b342d2b3f9a6a9a8",
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "size":{
                      "width":200,
                      "height":570}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"946f95b6695d4f138e5ba55d41d9a9fe",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"272a7f37f7dd42c3b342d2b3f9a6a9a8",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "size":{
                          "width":200,
                          "height":570}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/pravite/u7.png"}},
{
                  "id":"feb51bfcd22547c098b7a77784136d6d",
                  "label":"",
                  "parentDynamicPanel":"272a7f37f7dd42c3b342d2b3f9a6a9a8",
                  "type":"imageBox",
                  "styleType":"imageBox",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":64,
                      "y":150},
                    "size":{
                      "width":80,
                      "height":80}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"3bb7425af01d4351975da7ca0d11545b",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"272a7f37f7dd42c3b342d2b3f9a6a9a8",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":64,
                          "y":150},
                        "size":{
                          "width":80,
                          "height":80}},
                      "adaptiveStyles":{
}}],
                  "interactionMap":{
                    "onClick":{
                      "description":"OnClick",
                      "cases":[{
                          "description":"用例 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"linkWindow",
                              "description":"在 当前窗口 打开 picture",
                              "target":{
                                "targetType":"page",
                                "url":"picture.html",
                                "includeVariables":true},
                              "linkType":"current"}]}]}},
                  "tabbable":true,
                  "images":{
                    "normal~":"images/home/u62.JPG"}},
{
                  "id":"731ab865dfe347e29b5f91b9cede93e9",
                  "label":"",
                  "parentDynamicPanel":"272a7f37f7dd42c3b342d2b3f9a6a9a8",
                  "type":"buttonShape",
                  "styleType":"h1",
                  "visible":true,
                  "style":{
                    "fontSize":"12px",
                    "location":{
                      "x":73.5,
                      "y":245},
                    "size":{
                      "width":61,
                      "height":15}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"e76c2321b6324eaabf8c76a147239e78",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"272a7f37f7dd42c3b342d2b3f9a6a9a8",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontSize":"12px",
                        "location":{
                          "x":73.5,
                          "y":245},
                        "size":{
                          "width":61,
                          "height":15}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"54b22f8b6aef4561a190bcd9fd381381",
                  "label":"",
                  "parentDynamicPanel":"272a7f37f7dd42c3b342d2b3f9a6a9a8",
                  "type":"imageBox",
                  "styleType":"imageBox",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":63.5,
                      "y":40},
                    "size":{
                      "width":80,
                      "height":80}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"c15617be2acd4cbda90717323e551b94",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"272a7f37f7dd42c3b342d2b3f9a6a9a8",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":63.5,
                          "y":40},
                        "size":{
                          "width":80,
                          "height":80}},
                      "adaptiveStyles":{
}}],
                  "interactionMap":{
                    "onClick":{
                      "description":"OnClick",
                      "cases":[{
                          "description":"用例 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"linkWindow",
                              "description":"在 当前窗口 打开 creating",
                              "target":{
                                "targetType":"page",
                                "url":"creating.html",
                                "includeVariables":true},
                              "linkType":"current"}]}]}},
                  "tabbable":true,
                  "images":{
                    "normal~":"images/pravite/u13.png"}},
{
                  "id":"5631a2e1db28466e84115e56ec99dad9",
                  "label":"",
                  "parentDynamicPanel":"272a7f37f7dd42c3b342d2b3f9a6a9a8",
                  "type":"imageBox",
                  "styleType":"imageBox",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":64,
                      "y":280},
                    "size":{
                      "width":80,
                      "height":80}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"0fcba5374d6d43ffa0f3422b86ab4676",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"272a7f37f7dd42c3b342d2b3f9a6a9a8",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":64,
                          "y":280},
                        "size":{
                          "width":80,
                          "height":80}},
                      "adaptiveStyles":{
}}],
                  "interactionMap":{
                    "onClick":{
                      "description":"OnClick",
                      "cases":[{
                          "description":"用例 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"linkWindow",
                              "description":"在 当前窗口 打开 picture",
                              "target":{
                                "targetType":"page",
                                "url":"picture.html",
                                "includeVariables":true},
                              "linkType":"current"}]}]}},
                  "tabbable":true,
                  "images":{
                    "normal~":"images/home/u83.JPG"}},
{
                  "id":"b0d68feca03a4614923db042f28a77e5",
                  "label":"",
                  "parentDynamicPanel":"272a7f37f7dd42c3b342d2b3f9a6a9a8",
                  "type":"buttonShape",
                  "styleType":"h1",
                  "visible":true,
                  "style":{
                    "fontSize":"12px",
                    "location":{
                      "x":85.5,
                      "y":370},
                    "size":{
                      "width":37,
                      "height":15}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"ae1c5250e5ec4abcbcf3eea38d8dfd13",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"272a7f37f7dd42c3b342d2b3f9a6a9a8",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontSize":"12px",
                        "location":{
                          "x":85.5,
                          "y":370},
                        "size":{
                          "width":37,
                          "height":15}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"39858814004945368b0da783b5941f1d",
                  "label":"",
                  "parentDynamicPanel":"272a7f37f7dd42c3b342d2b3f9a6a9a8",
                  "type":"imageBox",
                  "styleType":"imageBox",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":64,
                      "y":415},
                    "size":{
                      "width":80,
                      "height":80}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"b2a23b791a8f45bda288d35c76fe2376",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"272a7f37f7dd42c3b342d2b3f9a6a9a8",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":64,
                          "y":415},
                        "size":{
                          "width":80,
                          "height":80}},
                      "adaptiveStyles":{
}}],
                  "interactionMap":{
                    "onClick":{
                      "description":"OnClick",
                      "cases":[{
                          "description":"用例 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"linkWindow",
                              "description":"在 当前窗口 打开 picture",
                              "target":{
                                "targetType":"page",
                                "url":"picture.html",
                                "includeVariables":true},
                              "linkType":"current"}]}]}},
                  "tabbable":true,
                  "images":{
                    "normal~":"images/home/u77.jpg"}},
{
                  "id":"6f2b0cfa15a544d8a680dce07426b4dd",
                  "label":"",
                  "parentDynamicPanel":"272a7f37f7dd42c3b342d2b3f9a6a9a8",
                  "type":"buttonShape",
                  "styleType":"h1",
                  "visible":true,
                  "style":{
                    "fontSize":"12px",
                    "location":{
                      "x":86,
                      "y":505},
                    "size":{
                      "width":37,
                      "height":15}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"c5e0fa76a52740fa88860c04b9bcd7ad",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"272a7f37f7dd42c3b342d2b3f9a6a9a8",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontSize":"12px",
                        "location":{
                          "x":86,
                          "y":505},
                        "size":{
                          "width":37,
                          "height":15}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"027d2d8feaab46459b4ac182025615b8",
                  "label":"",
                  "parentDynamicPanel":"272a7f37f7dd42c3b342d2b3f9a6a9a8",
                  "type":"imageBox",
                  "styleType":"imageBox",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":64,
                      "y":555},
                    "size":{
                      "width":80,
                      "height":80}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"95b5f95004424cfebbf323d0f5144068",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"272a7f37f7dd42c3b342d2b3f9a6a9a8",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":64,
                          "y":555},
                        "size":{
                          "width":80,
                          "height":80}},
                      "adaptiveStyles":{
}}],
                  "interactionMap":{
                    "onClick":{
                      "description":"OnClick",
                      "cases":[{
                          "description":"用例 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"linkWindow",
                              "description":"在 当前窗口 打开 picture",
                              "target":{
                                "targetType":"page",
                                "url":"picture.html",
                                "includeVariables":true},
                              "linkType":"current"}]}]}},
                  "tabbable":true,
                  "images":{
                    "normal~":"images/home/u115.JPG"}},
{
                  "id":"155eb60265dd4e71bb0fd01eefde5ec8",
                  "label":"",
                  "parentDynamicPanel":"272a7f37f7dd42c3b342d2b3f9a6a9a8",
                  "type":"buttonShape",
                  "styleType":"h1",
                  "visible":true,
                  "style":{
                    "fontSize":"12px",
                    "location":{
                      "x":86.5,
                      "y":645},
                    "size":{
                      "width":37,
                      "height":15}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"be57182690bf4077b7bc00fae0c65ab2",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"272a7f37f7dd42c3b342d2b3f9a6a9a8",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontSize":"12px",
                        "location":{
                          "x":86.5,
                          "y":645},
                        "size":{
                          "width":37,
                          "height":15}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}}]}]},
{
          "id":"c7cda6dd7f3a4831865e587c715c9b1a",
          "label":"private",
          "type":"dynamicPanel",
          "styleType":"dynamicPanel",
          "visible":true,
          "style":{
            "location":{
              "x":522,
              "y":112},
            "size":{
              "width":320,
              "height":568}},
          "adaptiveStyles":{
},
          "interactionMap":{
            "onSwipeLeft":{
              "description":"OnSwipeLeft",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"moveWidget",
                      "description":"移动 private 相对位置为 (-200,0) 线性 500ms",
                      "objectsToMoves":[{
                          "objectPath":["c7cda6dd7f3a4831865e587c715c9b1a"],
                          "moveInfo":{
                            "moveType":"delta",
                            "xValue":{
                              "exprType":"stringLiteral",
                              "value":"-200",
                              "stos":[]},
                            "yValue":{
                              "exprType":"stringLiteral",
                              "value":"0",
                              "stos":[]},
                            "options":{
                              "easing":"linear",
                              "duration":500}}}]},
{
                      "action":"setFunction",
                      "description":"设置 值于 isHiden2 = &quot;true&quot;",
                      "expr":{
                        "exprType":"block",
                        "subExprs":[{
                            "exprType":"fcall",
                            "functionName":"SetGlobalVariableValue",
                            "arguments":[{
                                "exprType":"globalVariableLiteral",
                                "variableName":"isHiden2"},
{
                                "exprType":"stringLiteral",
                                "value":"true",
                                "stos":[]}]}]}}]}]},
            "onSwipeRight":{
              "description":"OnSwipeRight",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"moveWidget",
                      "description":"移动 private 相对位置为 (200,0) 线性 500ms",
                      "objectsToMoves":[{
                          "objectPath":["c7cda6dd7f3a4831865e587c715c9b1a"],
                          "moveInfo":{
                            "moveType":"delta",
                            "xValue":{
                              "exprType":"stringLiteral",
                              "value":"200",
                              "stos":[]},
                            "yValue":{
                              "exprType":"stringLiteral",
                              "value":"0",
                              "stos":[]},
                            "options":{
                              "easing":"linear",
                              "duration":500}}}]},
{
                      "action":"setFunction",
                      "description":"设置 值于 isHiden2 = &quot;false&quot;",
                      "expr":{
                        "exprType":"block",
                        "subExprs":[{
                            "exprType":"fcall",
                            "functionName":"SetGlobalVariableValue",
                            "arguments":[{
                                "exprType":"globalVariableLiteral",
                                "variableName":"isHiden2"},
{
                                "exprType":"stringLiteral",
                                "value":"false",
                                "stos":[]}]}]}}]}]}},
          "scrollbars":"none",
          "fitToContent":false,
          "propagate":false,
          "diagrams":[{
              "id":"d76de494441f4f16a2c70abdca6d9b90",
              "label":"State1",
              "type":"Axure:PanelDiagram",
              "objects":[{
                  "id":"aeae9afb62b249c2b012e70b0a328953",
                  "label":"",
                  "parentDynamicPanel":"c7cda6dd7f3a4831865e587c715c9b1a",
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":0,
                      "y":248},
                    "size":{
                      "width":320,
                      "height":320}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"4c9a814f3bd74a04838facdf177c03fb",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"c7cda6dd7f3a4831865e587c715c9b1a",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":0,
                          "y":248},
                        "size":{
                          "width":320,
                          "height":320}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/pravite/u28.png"}},
{
                  "id":"0e916c58a2b54f9f8f3e3661da155063",
                  "label":"世界地图",
                  "parentDynamicPanel":"c7cda6dd7f3a4831865e587c715c9b1a",
                  "type":"imageBox",
                  "styleType":"imageBox",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":0,
                      "y":270},
                    "size":{
                      "width":320,
                      "height":262}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"870295df3fe74d7eb7f12d1da5b73630",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"c7cda6dd7f3a4831865e587c715c9b1a",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":0,
                          "y":270},
                        "size":{
                          "width":320,
                          "height":262}},
                      "adaptiveStyles":{
}}],
                  "interactionMap":{
                    "onClick":{
                      "description":"OnClick",
                      "cases":[{
                          "description":"用例 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"moveWidget",
                              "description":"移动 广东省地图 到 (0,280) 线性 500ms",
                              "objectsToMoves":[{
                                  "objectPath":["92b08546204e4050a250ef2f712e5693"],
                                  "moveInfo":{
                                    "moveType":"location",
                                    "xValue":{
                                      "exprType":"stringLiteral",
                                      "value":"0",
                                      "stos":[]},
                                    "yValue":{
                                      "exprType":"stringLiteral",
                                      "value":"280",
                                      "stos":[]},
                                    "options":{
                                      "easing":"linear",
                                      "duration":500}}}]}]}]}},
                  "tabbable":true,
                  "images":{
                    "normal~":"images/pravite/世界地图_u30.jpg"}},
{
                  "id":"e58e7fe86eec4c19be7903855ead980a",
                  "label":"",
                  "parentDynamicPanel":"c7cda6dd7f3a4831865e587c715c9b1a",
                  "type":"imageBox",
                  "styleType":"imageBox",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":0,
                      "y":60},
                    "size":{
                      "width":320,
                      "height":182},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFFFFFF}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"c415a3584c894bdf8d7df676794f3663",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"c7cda6dd7f3a4831865e587c715c9b1a",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":0,
                          "y":60},
                        "size":{
                          "width":320,
                          "height":182},
                        "borderFill":{
                          "fillType":"solid",
                          "color":0xFFFFFF}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/pravite/u32.jpg"}},
{
                  "id":"d6bd6899e98c4b19aaf673b914070cc2",
                  "label":"",
                  "parentDynamicPanel":"c7cda6dd7f3a4831865e587c715c9b1a",
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":-10,
                      "y":240},
                    "size":{
                      "width":330,
                      "height":72},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFFFFFF}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"24c23662e3cd40c4865e306e16a5c093",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"c7cda6dd7f3a4831865e587c715c9b1a",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":-10,
                          "y":240},
                        "size":{
                          "width":330,
                          "height":72},
                        "borderFill":{
                          "fillType":"solid",
                          "color":0xFFFFFF}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/pravite/u34.png"}},
{
                  "id":"80642e0fd34844faa3f31baf40ea30e7",
                  "label":"状态栏",
                  "parentDynamicPanel":"c7cda6dd7f3a4831865e587c715c9b1a",
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFFF6666},
                    "size":{
                      "width":320,
                      "height":20},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFFFF6666}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"feda5b10ebd74d0ab5bf65b5845cba1d",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"c7cda6dd7f3a4831865e587c715c9b1a",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fill":{
                          "fillType":"solid",
                          "color":0xFFFF6666},
                        "size":{
                          "width":320,
                          "height":20},
                        "borderFill":{
                          "fillType":"solid",
                          "color":0xFFFF6666}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/home/状态栏_u31.png"}},
{
                  "id":"f19f2b2e35044a5d8ca263ce80aaf057",
                  "label":"",
                  "parentDynamicPanel":"c7cda6dd7f3a4831865e587c715c9b1a",
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "fontName":"'Charlemagne Std Bold', 'Charlemagne Std'",
                    "fontSize":"14px",
                    "fontWeight":"700",
                    "lineSpacing":"20px",
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFFF6666},
                    "location":{
                      "x":0,
                      "y":20},
                    "size":{
                      "width":320,
                      "height":40},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFFFF6666}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"d0606f10b971415dbc47712862dd754a",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"c7cda6dd7f3a4831865e587c715c9b1a",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontName":"'Charlemagne Std Bold', 'Charlemagne Std'",
                        "fontSize":"14px",
                        "fontWeight":"700",
                        "lineSpacing":"20px",
                        "fill":{
                          "fillType":"solid",
                          "color":0xFFFF6666},
                        "location":{
                          "x":0,
                          "y":20},
                        "size":{
                          "width":320,
                          "height":40},
                        "borderFill":{
                          "fillType":"solid",
                          "color":0xFFFF6666}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/home/框架_u33.png"}},
{
                  "id":"975045523f2f4967acb169e90697a960",
                  "label":"",
                  "parentDynamicPanel":"c7cda6dd7f3a4831865e587c715c9b1a",
                  "type":"imageBox",
                  "styleType":"imageBox",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":114.5,
                      "y":70},
                    "size":{
                      "width":91,
                      "height":90}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"00b7336a74e3464ea7e6a01a7249002f",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"c7cda6dd7f3a4831865e587c715c9b1a",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":114.5,
                          "y":70},
                        "size":{
                          "width":91,
                          "height":90}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/home/u5.png"}},
{
                  "id":"f2f671cbd3854abeba2523eedfdb9eef",
                  "label":"",
                  "parentDynamicPanel":"c7cda6dd7f3a4831865e587c715c9b1a",
                  "type":"buttonShape",
                  "styleType":"h1",
                  "visible":true,
                  "style":{
                    "fontName":"'微软雅黑 Regular', '微软雅黑'",
                    "fontSize":"20px",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFFFFFFFF,
                      "opacity":1},
                    "location":{
                      "x":120,
                      "y":26},
                    "size":{
                      "width":81,
                      "height":27}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"e5e103ea69cc4ab78bbeb46555340609",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"c7cda6dd7f3a4831865e587c715c9b1a",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontName":"'微软雅黑 Regular', '微软雅黑'",
                        "fontSize":"20px",
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFFFFFFFF,
                          "opacity":1},
                        "location":{
                          "x":120,
                          "y":26},
                        "size":{
                          "width":81,
                          "height":27}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"bf0882dffc27414ba869e35623627c4b",
                  "label":"消息",
                  "parentDynamicPanel":"c7cda6dd7f3a4831865e587c715c9b1a",
                  "type":"imageBox",
                  "styleType":"imageBox",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":10,
                      "y":30},
                    "size":{
                      "width":25,
                      "height":25}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"970fec293329437aa61d4c8e382fa052",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"c7cda6dd7f3a4831865e587c715c9b1a",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":10,
                          "y":30},
                        "size":{
                          "width":25,
                          "height":25}},
                      "adaptiveStyles":{
}}],
                  "interactionMap":{
                    "onClick":{
                      "description":"OnClick",
                      "cases":[{
                          "description":"用例 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"linkWindow",
                              "description":"在 当前窗口 打开 Home",
                              "target":{
                                "targetType":"page",
                                "url":"home.html",
                                "includeVariables":true},
                              "linkType":"current"}]}]}},
                  "tabbable":true,
                  "images":{
                    "normal~":"images/pravite/消息_u44.png"}},
{
                  "id":"3d2c6230a0a6466d863565bfaa86765b",
                  "label":"",
                  "parentDynamicPanel":"c7cda6dd7f3a4831865e587c715c9b1a",
                  "type":"horizontalLine",
                  "styleType":"horizontalLine",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":0,
                      "y":238},
                    "size":{
                      "width":320,
                      "height":10},
                    "borderWidth":"5",
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFFFF6666}},
                  "adaptiveStyles":{
},
                  "images":{
                    "start~":"resources/images/transparent.gif",
                    "end~":"resources/images/transparent.gif",
                    "line~":"images/home/u146_line.png"}},
{
                  "id":"5552e498287a4b3498b8ee2e99c3cfd9",
                  "label":"",
                  "parentDynamicPanel":"c7cda6dd7f3a4831865e587c715c9b1a",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFFFFFFFF,
                      "opacity":1},
                    "location":{
                      "x":50,
                      "y":184},
                    "size":{
                      "width":27,
                      "height":16}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"e2d1c10948764d4ea36428b9f06aedbf",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"c7cda6dd7f3a4831865e587c715c9b1a",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFFFFFFFF,
                          "opacity":1},
                        "location":{
                          "x":50,
                          "y":184},
                        "size":{
                          "width":27,
                          "height":16}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"09aacc58690f493e9aa73c813b3b1fa1",
                  "label":"",
                  "parentDynamicPanel":"c7cda6dd7f3a4831865e587c715c9b1a",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFFFFFFFF,
                      "opacity":1},
                    "location":{
                      "x":146,
                      "y":184},
                    "size":{
                      "width":27,
                      "height":16}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"c4b934910aa94b3a8037a5adbc630367",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"c7cda6dd7f3a4831865e587c715c9b1a",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFFFFFFFF,
                          "opacity":1},
                        "location":{
                          "x":146,
                          "y":184},
                        "size":{
                          "width":27,
                          "height":16}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"d159ef8e74e244c9bf57b0d0ad793156",
                  "label":"",
                  "parentDynamicPanel":"c7cda6dd7f3a4831865e587c715c9b1a",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFFFFFFFF,
                      "opacity":1},
                    "location":{
                      "x":56,
                      "y":200},
                    "size":{
                      "width":15,
                      "height":34}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"a0258bbc7a9c4864884d3672b93b033f",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"c7cda6dd7f3a4831865e587c715c9b1a",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFFFFFFFF,
                          "opacity":1},
                        "location":{
                          "x":56,
                          "y":200},
                        "size":{
                          "width":15,
                          "height":34}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"066e760833284c41a68ab632fa876404",
                  "label":"",
                  "parentDynamicPanel":"c7cda6dd7f3a4831865e587c715c9b1a",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFFFFFFFF,
                      "opacity":1},
                    "location":{
                      "x":146,
                      "y":200},
                    "size":{
                      "width":29,
                      "height":34}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"2d45d173139845cf9c726faea4a02014",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"c7cda6dd7f3a4831865e587c715c9b1a",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFFFFFFFF,
                          "opacity":1},
                        "location":{
                          "x":146,
                          "y":200},
                        "size":{
                          "width":29,
                          "height":34}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"738ae3dcc62b433bb8f4006a1d5a8d6c",
                  "label":"",
                  "parentDynamicPanel":"c7cda6dd7f3a4831865e587c715c9b1a",
                  "type":"horizontalLine",
                  "styleType":"horizontalLine",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":0,
                      "y":558},
                    "size":{
                      "width":320,
                      "height":10},
                    "borderWidth":"5",
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFFFF6666}},
                  "adaptiveStyles":{
},
                  "images":{
                    "start~":"resources/images/transparent.gif",
                    "end~":"resources/images/transparent.gif",
                    "line~":"images/home/u146_line.png"}},
{
                  "id":"7161b0cd743f4bb58070f13016f0fe93",
                  "label":"中国地图",
                  "parentDynamicPanel":"c7cda6dd7f3a4831865e587c715c9b1a",
                  "type":"imageBox",
                  "styleType":"imageBox",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":350,
                      "y":258},
                    "size":{
                      "width":320,
                      "height":262}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"413c5d0ae0d74c9e91d8465fe8c019db",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"c7cda6dd7f3a4831865e587c715c9b1a",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":350,
                          "y":258},
                        "size":{
                          "width":320,
                          "height":262}},
                      "adaptiveStyles":{
}}],
                  "interactionMap":{
                    "onClick":{
                      "description":"OnClick",
                      "cases":[{
                          "description":"用例 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"moveWidget",
                              "description":"移动 广东省地图 到 (0,280) 线性 500ms",
                              "objectsToMoves":[{
                                  "objectPath":["92b08546204e4050a250ef2f712e5693"],
                                  "moveInfo":{
                                    "moveType":"location",
                                    "xValue":{
                                      "exprType":"stringLiteral",
                                      "value":"0",
                                      "stos":[]},
                                    "yValue":{
                                      "exprType":"stringLiteral",
                                      "value":"280",
                                      "stos":[]},
                                    "options":{
                                      "easing":"linear",
                                      "duration":500}}}]}]}]}},
                  "tabbable":true,
                  "images":{
                    "normal~":"images/pravite/中国地图_u56.jpg"}},
{
                  "id":"92b08546204e4050a250ef2f712e5693",
                  "label":"广东省地图",
                  "parentDynamicPanel":"c7cda6dd7f3a4831865e587c715c9b1a",
                  "type":"imageBox",
                  "styleType":"imageBox",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":350,
                      "y":280},
                    "size":{
                      "width":320,
                      "height":262}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"06c87abf3aff4f07996a8fb7ac1cfde4",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"c7cda6dd7f3a4831865e587c715c9b1a",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":350,
                          "y":280},
                        "size":{
                          "width":320,
                          "height":262}},
                      "adaptiveStyles":{
}}],
                  "interactionMap":{
                    "onClick":{
                      "description":"OnClick",
                      "cases":[{
                          "description":"用例 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"moveWidget",
                              "description":"移动 旅游线路图 到 (0,280) 线性 500ms",
                              "objectsToMoves":[{
                                  "objectPath":["81a77ec64443446d98c4cc0d906e5040"],
                                  "moveInfo":{
                                    "moveType":"location",
                                    "xValue":{
                                      "exprType":"stringLiteral",
                                      "value":"0",
                                      "stos":[]},
                                    "yValue":{
                                      "exprType":"stringLiteral",
                                      "value":"280",
                                      "stos":[]},
                                    "options":{
                                      "easing":"linear",
                                      "duration":500}}}]}]}]}},
                  "tabbable":true,
                  "images":{
                    "normal~":"images/pravite/广东省地图_u58.jpg"}},
{
                  "id":"81a77ec64443446d98c4cc0d906e5040",
                  "label":"旅游线路图",
                  "parentDynamicPanel":"c7cda6dd7f3a4831865e587c715c9b1a",
                  "type":"imageBox",
                  "styleType":"imageBox",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":350,
                      "y":280},
                    "size":{
                      "width":320,
                      "height":262}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"464fce4cc1294829a2e9a0d6225e7131",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"c7cda6dd7f3a4831865e587c715c9b1a",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":350,
                          "y":280},
                        "size":{
                          "width":320,
                          "height":262}},
                      "adaptiveStyles":{
}}],
                  "interactionMap":{
                    "onClick":{
                      "description":"OnClick",
                      "cases":[{
                          "description":"用例 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"linkWindow",
                              "description":"在 当前窗口 打开 picture",
                              "target":{
                                "targetType":"page",
                                "url":"picture.html",
                                "includeVariables":true},
                              "linkType":"current"}]}]}},
                  "tabbable":true,
                  "images":{
                    "normal~":"images/pravite/旅游线路图_u60.png"}},
{
                  "id":"ae9366beca164528a24b8b599cbf67a5",
                  "label":"",
                  "parentDynamicPanel":"c7cda6dd7f3a4831865e587c715c9b1a",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFFFFFFFF,
                      "opacity":1},
                    "location":{
                      "x":231,
                      "y":184},
                    "size":{
                      "width":27,
                      "height":16}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"cadc6b9ea3a3420a9b831903cce6efe4",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"c7cda6dd7f3a4831865e587c715c9b1a",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFFFFFFFF,
                          "opacity":1},
                        "location":{
                          "x":231,
                          "y":184},
                        "size":{
                          "width":27,
                          "height":16}},
                      "adaptiveStyles":{
}}],
                  "interactionMap":{
                    "onClick":{
                      "description":"OnClick",
                      "cases":[{
                          "description":"用例 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"linkWindow",
                              "description":"在 当前窗口 打开 achievement",
                              "target":{
                                "targetType":"page",
                                "url":"achievement.html",
                                "includeVariables":true},
                              "linkType":"current"}]}]}},
                  "tabbable":true,
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"934b76965ba344e1a49b5e2282ac2139",
                  "label":"",
                  "parentDynamicPanel":"c7cda6dd7f3a4831865e587c715c9b1a",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFFFFFFFF,
                      "opacity":1},
                    "location":{
                      "x":237,
                      "y":200},
                    "size":{
                      "width":15,
                      "height":34}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"daeb70b40b8e461b81b701c2571fe0f6",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"c7cda6dd7f3a4831865e587c715c9b1a",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFFFFFFFF,
                          "opacity":1},
                        "location":{
                          "x":237,
                          "y":200},
                        "size":{
                          "width":15,
                          "height":34}},
                      "adaptiveStyles":{
}}],
                  "interactionMap":{
                    "onClick":{
                      "description":"OnClick",
                      "cases":[{
                          "description":"用例 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"linkWindow",
                              "description":"在 当前窗口 打开 achievement",
                              "target":{
                                "targetType":"page",
                                "url":"achievement.html",
                                "includeVariables":true},
                              "linkType":"current"}]}]}},
                  "tabbable":true,
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"038e28fe41424e6e8e1078e9e94d5766",
                  "label":"",
                  "parentDynamicPanel":"c7cda6dd7f3a4831865e587c715c9b1a",
                  "type":"imageBox",
                  "styleType":"imageBox",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":280,
                      "y":24},
                    "size":{
                      "width":30,
                      "height":30}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"da096658fc8047b8a5fa80a9653997bf",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"c7cda6dd7f3a4831865e587c715c9b1a",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":280,
                          "y":24},
                        "size":{
                          "width":30,
                          "height":30}},
                      "adaptiveStyles":{
}}],
                  "interactionMap":{
                    "onClick":{
                      "description":"OnClick",
                      "cases":[{
                          "description":"用例 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"linkWindow",
                              "description":"在 当前窗口 打开 settings",
                              "target":{
                                "targetType":"page",
                                "url":"settings.html",
                                "includeVariables":true},
                              "linkType":"current"}]}]}},
                  "tabbable":true,
                  "images":{
                    "normal~":"images/pravite/u66.png"}}]}]},
{
          "id":"23928127a8cd41979b9d14667f19b1c7",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":842,
              "y":0},
            "size":{
              "width":240,
              "height":768}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c770cac36d7942b8b91f466071bda3d4",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":842,
                  "y":0},
                "size":{
                  "width":240,
                  "height":768}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/pravite/u68.png"}}]}},
  "masters":{
},
  "objectPaths":{
    "86894ea838eb4b97b65a12f9a5611989":{
      "scriptId":"u0"},
    "218ac75ffa0144c7a8ab950760360a9e":{
      "scriptId":"u1"},
    "4186b90d44cb43e0a621520bf6e8c7de":{
      "scriptId":"u2"},
    "34ffd273a28b4b7dbd47fca3d9480821":{
      "scriptId":"u3"},
    "d70b9aaa4ad64b7b92649b828031464e":{
      "scriptId":"u4"},
    "de714c94323a44c7a875bad4fbd33ef6":{
      "scriptId":"u5"},
    "272a7f37f7dd42c3b342d2b3f9a6a9a8":{
      "scriptId":"u6"},
    "5cf7e0063fcd4b2c95540802ef757a05":{
      "scriptId":"u7"},
    "946f95b6695d4f138e5ba55d41d9a9fe":{
      "scriptId":"u8"},
    "feb51bfcd22547c098b7a77784136d6d":{
      "scriptId":"u9"},
    "3bb7425af01d4351975da7ca0d11545b":{
      "scriptId":"u10"},
    "731ab865dfe347e29b5f91b9cede93e9":{
      "scriptId":"u11"},
    "e76c2321b6324eaabf8c76a147239e78":{
      "scriptId":"u12"},
    "54b22f8b6aef4561a190bcd9fd381381":{
      "scriptId":"u13"},
    "c15617be2acd4cbda90717323e551b94":{
      "scriptId":"u14"},
    "5631a2e1db28466e84115e56ec99dad9":{
      "scriptId":"u15"},
    "0fcba5374d6d43ffa0f3422b86ab4676":{
      "scriptId":"u16"},
    "b0d68feca03a4614923db042f28a77e5":{
      "scriptId":"u17"},
    "ae1c5250e5ec4abcbcf3eea38d8dfd13":{
      "scriptId":"u18"},
    "39858814004945368b0da783b5941f1d":{
      "scriptId":"u19"},
    "b2a23b791a8f45bda288d35c76fe2376":{
      "scriptId":"u20"},
    "6f2b0cfa15a544d8a680dce07426b4dd":{
      "scriptId":"u21"},
    "c5e0fa76a52740fa88860c04b9bcd7ad":{
      "scriptId":"u22"},
    "027d2d8feaab46459b4ac182025615b8":{
      "scriptId":"u23"},
    "95b5f95004424cfebbf323d0f5144068":{
      "scriptId":"u24"},
    "155eb60265dd4e71bb0fd01eefde5ec8":{
      "scriptId":"u25"},
    "be57182690bf4077b7bc00fae0c65ab2":{
      "scriptId":"u26"},
    "c7cda6dd7f3a4831865e587c715c9b1a":{
      "scriptId":"u27"},
    "aeae9afb62b249c2b012e70b0a328953":{
      "scriptId":"u28"},
    "4c9a814f3bd74a04838facdf177c03fb":{
      "scriptId":"u29"},
    "0e916c58a2b54f9f8f3e3661da155063":{
      "scriptId":"u30"},
    "870295df3fe74d7eb7f12d1da5b73630":{
      "scriptId":"u31"},
    "e58e7fe86eec4c19be7903855ead980a":{
      "scriptId":"u32"},
    "c415a3584c894bdf8d7df676794f3663":{
      "scriptId":"u33"},
    "d6bd6899e98c4b19aaf673b914070cc2":{
      "scriptId":"u34"},
    "24c23662e3cd40c4865e306e16a5c093":{
      "scriptId":"u35"},
    "80642e0fd34844faa3f31baf40ea30e7":{
      "scriptId":"u36"},
    "feda5b10ebd74d0ab5bf65b5845cba1d":{
      "scriptId":"u37"},
    "f19f2b2e35044a5d8ca263ce80aaf057":{
      "scriptId":"u38"},
    "d0606f10b971415dbc47712862dd754a":{
      "scriptId":"u39"},
    "975045523f2f4967acb169e90697a960":{
      "scriptId":"u40"},
    "00b7336a74e3464ea7e6a01a7249002f":{
      "scriptId":"u41"},
    "f2f671cbd3854abeba2523eedfdb9eef":{
      "scriptId":"u42"},
    "e5e103ea69cc4ab78bbeb46555340609":{
      "scriptId":"u43"},
    "bf0882dffc27414ba869e35623627c4b":{
      "scriptId":"u44"},
    "970fec293329437aa61d4c8e382fa052":{
      "scriptId":"u45"},
    "3d2c6230a0a6466d863565bfaa86765b":{
      "scriptId":"u46"},
    "5552e498287a4b3498b8ee2e99c3cfd9":{
      "scriptId":"u47"},
    "e2d1c10948764d4ea36428b9f06aedbf":{
      "scriptId":"u48"},
    "09aacc58690f493e9aa73c813b3b1fa1":{
      "scriptId":"u49"},
    "c4b934910aa94b3a8037a5adbc630367":{
      "scriptId":"u50"},
    "d159ef8e74e244c9bf57b0d0ad793156":{
      "scriptId":"u51"},
    "a0258bbc7a9c4864884d3672b93b033f":{
      "scriptId":"u52"},
    "066e760833284c41a68ab632fa876404":{
      "scriptId":"u53"},
    "2d45d173139845cf9c726faea4a02014":{
      "scriptId":"u54"},
    "738ae3dcc62b433bb8f4006a1d5a8d6c":{
      "scriptId":"u55"},
    "7161b0cd743f4bb58070f13016f0fe93":{
      "scriptId":"u56"},
    "413c5d0ae0d74c9e91d8465fe8c019db":{
      "scriptId":"u57"},
    "92b08546204e4050a250ef2f712e5693":{
      "scriptId":"u58"},
    "06c87abf3aff4f07996a8fb7ac1cfde4":{
      "scriptId":"u59"},
    "81a77ec64443446d98c4cc0d906e5040":{
      "scriptId":"u60"},
    "464fce4cc1294829a2e9a0d6225e7131":{
      "scriptId":"u61"},
    "ae9366beca164528a24b8b599cbf67a5":{
      "scriptId":"u62"},
    "cadc6b9ea3a3420a9b831903cce6efe4":{
      "scriptId":"u63"},
    "934b76965ba344e1a49b5e2282ac2139":{
      "scriptId":"u64"},
    "daeb70b40b8e461b81b701c2571fe0f6":{
      "scriptId":"u65"},
    "038e28fe41424e6e8e1078e9e94d5766":{
      "scriptId":"u66"},
    "da096658fc8047b8a5fa80a9653997bf":{
      "scriptId":"u67"},
    "23928127a8cd41979b9d14667f19b1c7":{
      "scriptId":"u68"},
    "c770cac36d7942b8b91f466071bda3d4":{
      "scriptId":"u69"}}});